### ISSUE TITLE
[FEATURE] Expand To Load Favorite Avatars

### ISSUE THREAD

**Issue by Garoam** [emmVRC/emmVRC-Public#106]
Having a large amount of favorite avatars causes my game to stutter for upwards of three minutes if I don't close the avatar menu before about ten seconds, and it makes searching for avatars take much longer than it should. Would it be possible to make it so you have to expand the favorite avatars list to load it, similarly to offline friends or avatar worlds? That way I won't have to wait forever to search for an avatar.

**Comment by Nathan43615** [comment]
Favorites hidden/collapsed by default, PLUS having avatars split into sections of 100 each, would definitely help with avatar menu lag.
