### ISSUE TITLE
[FEATURE] Risky functions disable when a VRChat Team member is in the instance you're in

### ISSUE THREAD

**Issue by BLANKE1** [emmVRC/emmVRC-Public#109]
As the title says^ would provide a bit more protection to the users

**Comment by yui-123** [comment]
the issue is most of the moderators dont have admin perms on there account thay go around in as thats to easy to detect along with most bans are cause you get reported or someone records you and sends it in to vrc

**Comment by thetrueyoshifan** [comment]
This is unfortunately not very doable, as VRChat staff can just not use a staff account, or toggle their permissions and things of that sort.
