### ISSUE TITLE
[Feature] Additions to Stealth Mode

### ISSUE THREAD

**Issue by Nathan43615** [emmVRC/emmVRC-Public#110]
**I want to make VRChat content on YouTube and twitch and I love using EmmVRC and don’t want to uninstall it when making content but there’s still some more features that need to be moved/hidden for Stealth Mode to actually be “stealthy”.**

The main thing is that the EmmVRC favorites should be moved to the bottom row of the Avatar menu instead of the top, and the EmmVRC Favorite button should be either at the bottom of the page as well or make it appear only after clicking the regular favorite button.

Also there is some features that are completely inaccessible when using stealth mode, like dropping a portal to a friend’s instance and the other features from the EmmVRC functions in the social menu. Maybe these could be hidden in the “report user” button.

What doesn’t make much sense is the lack of consistency, how the EmmVRC functions button is completely visible in the “Mini Social Menu thing” where you show/hide avatars and stuff (unlike the social menu functions button, which doesn’t exist, stated above), when that menu is sometimes visited more often than the social menu, at least for me. Maybe that button can also be hidden in the report user button.

**Comment by BenjaminZehowlt** [comment]
Stealth mode is no longer a feature of emmVRC.
