### ISSUE TITLE
[BUG] Notification button not working when pressed

### ISSUE THREAD

**Issue by sleepytimes** [emmVRC/emmVRC-Public#113]
The notification button on the quick menu seems to have suddenly stopped working for me. Whenever I press on the button nothing shows, basically not letting me log into my emm account.
When i do press it this error message shows on MelonLoader
![image](https://user-images.githubusercontent.com/74684744/99596763-de9b9880-29c4-11eb-912b-b712de12cae6.png)

It seems to only happen when i play Vrchat through the Oculus library, as when I play through SteamVR its perfectly fine. Both MelonLoader and Emmvrc are up to date.

**Comment by Provini** [comment]
This is because VRChat has not pushed Build 1017 to Oculus yet.

**Comment by thetrueyoshifan** [comment]
Fixed with emmVRC 2.2.5
