### ISSUE TITLE
[FEATURE] Personal Icon in nameplate

### ISSUE THREAD

**Issue by cub28** [emmVRC/emmVRC-Public#1283]
we could upload a pic for our nameplate in vrchat

**Comment by rakosi2** [comment]
I am going to assume that you are referring to the new icon the was introduced with VRC+. At the moment I don't think we can add the icon as emm only changes what happens locally on your computer and not on other user's other then some risky features. This would require us the somehow fake to other clients that we have VRC+ which I don't think we can do. We could take a look once VRC+ subscriptions goes live if faking it is possible but I doubt it.

**Comment by cub28** [comment]
Thanks
________________________________
