### ISSUE TITLE
[Bug Report] Keybinds

### ISSUE THREAD

**Issue by CrimsonMoonFQ** [emmVRC/emmVRC-Public#1285]
I was rebinding some of the keys for the functions and noticed a few didnt work or atleast do anything when I used/changed them in game.

![Keybind](https://user-images.githubusercontent.com/73706742/99918402-3cd5bd80-2cdc-11eb-9c1c-542926ff313c.PNG)

**Comment by thetrueyoshifan** [comment]
Will be fixed in emmVRC 2.4.1
