### ISSUE TITLE
[Feature] FPS Limiter

### ISSUE THREAD

**Issue by SodaShot** [emmVRC/emmVRC-Public#1290]
Capability: This feature will limit the Frames per second (FPS) for the entirety of VRChat & will help with people who want to limit the CPU Usage Vrchat will overall use.
This feature benefits & Helps the users who do not have a great PC & want to be able to watch youtube etc without VRchat taking all the CPU & GPU Power.

As of now their already is a FPS Limiter located in the VRChat Modding Group but it isn't being worked on to my understanding & a abandoned project.

**Comment by Janni9009** [comment]
This already exists as part of Unity (-fps XX in launch options where X is your target framerate) and emmVRC (see: config.json in your VRChat\UserData\ directory).
Both of these systems wont work in VR as your compositor controls framerate there. (That being Oculus, SteamVR or whatever you may use, both of which have their own lag compensation built in, being Asyncronous SpaceWarp for Oculus, and Motion Smoothing for SteamVR).
