### ISSUE TITLE
[Bug] Social refresh not working

### ISSUE THREAD

**Issue by ChinatsuHS** [emmVRC/emmVRC-Public#1292]
Since a while i come to notice that refresh on the social tab is not working and it even disables vrchats own automatic refresh.

Only way to refresh social is by restarting the game.

**Comment by rakosi2** [comment]
Could you post your latest MelonLoader log file here or in the discord https://discord.gg/emmvrc? You can find it in VRChat\Logs.

**Comment by ChinatsuHS** [comment]
[MelonLoader_20-12-03_17-31-32.589.log](https://github.com/emmVRC/emmVRC-Public/files/5638013/MelonLoader_20-12-03_17-31-32.589.log)

here you go

**Comment by ChinatsuHS** [comment]
recent update seems to have fixed the issue
