### ISSUE TITLE
[FEATURE] Togglable CyanLaser Climbing Prefab

### ISSUE THREAD

**Issue by sokkacount** [emmVRC/emmVRC-Public#1294]
Like the flashlight prefab, but instead it's CyanLaser's climbing prefab. Add it to risky functions since it would count as a non-vanilla form of movement.

**Comment by Janni9009** [comment]
From what i recall that system requires a special world setup to function, this is probably not going to work if that's the case.
As an alternative OVR-AdvancedSettings allows you to simulate climbing.
