### ISSUE TITLE
[FEATURE]Adblock

### ISSUE THREAD

**Issue by Kilowog01** [emmVRC/emmVRC-Public#1295]
I will never give money to VR chat as long as they maintain their current behavior. With that said, I also don't want to see ads being forced into my throat. Can we have a feature to remove all mentions to VRC +? Like the tab in the main menu, the ad in the esc menu, the other one in the avatar menu, etc...

**Comment by Provini** [comment]
Already in emmVRC. emmVRC Functions > Settings > Page 7.
