### ISSUE TITLE
[Bug Report] VRC+ avi fav ad

### ISSUE THREAD

**Issue by CrimsonMoonFQ** [emmVRC/emmVRC-Public#1296]
So when I activate the disable all the VRC+ ads button this ad still shows in the fav list.
![snip](https://user-images.githubusercontent.com/73706742/101095306-5a7c1000-3583-11eb-8723-3f1a5843533a.PNG)

**Comment by ShaunDreclin** [comment]
Just came here to request the same thing! Such an obnoxious button...

**Comment by thetrueyoshifan** [comment]
Will be fixed with emmVRC 2.4.1
