### ISSUE TITLE
Loading Screen Music Playlist

### ISSUE THREAD

**Issue by CappyGameDev** [emmVRC/emmVRC-Public#1297]
Currently as emm stands, Music is played via a single menumusic.ogg file.

Something I think could be very useful and awesome to do, would be instead putting this feature into a folder named "Menu Music" which emmvrc will then randomly choose songs from within that folder to play each time you enter the loading screen, that way the music is much more diverse and you always get a new song to listen to!

**Comment by rakosi2** [comment]
Currently, it should be called custommenu.ogg

**Comment by thetrueyoshifan** [comment]
Added several emmVRC versions ago
