### ISSUE TITLE
[Bug Report] HUD off doesn't save

### ISSUE THREAD

**Issue by ogatasaan** [emmVRC/emmVRC-Public#1299]
Before last update, HUD (in UI Elements) was saving. now it doesn't work.

**Comment by Provini** [comment]
This is bug with the new VRChat update as the same occurs when no mods are loaded.

**Comment by thetrueyoshifan** [comment]
emmVRC allowed the states of both HUD toggles and nameplate toggles to persist across restarts. This broke with the VRChat+ update, and is still something I want to fix

**Comment by thetrueyoshifan** [comment]
Will be fixed with emmVRC 2.4.1
