### ISSUE TITLE
[Feature] Editing notes in emmVRC

### ISSUE THREAD

**Issue by miguelgdx** [emmVRC/emmVRC-Public#1307]
Apparently, if you already have a emmVRC note on someone and you try to edit it, the text area appears blank, without letting you append more information.
This is a bit annoying if you are using VR. If you're on desktop, you either have to retype everything or edit the JSON file directly.

Could the edit text area be loaded with the current info?

**Comment by thetrueyoshifan** [comment]
Will be added in emmVRC 2.4.1
