### ISSUE TITLE
[Bug] Instant Restart/Force Quit no longer properly drop you from the world.

### ISSUE THREAD

**Issue by Provini** [emmVRC/emmVRC-Public#1311]
2.0.0 patch note:
- Force Quit and Instant Restart will now properly drop you from the world before closing the game, so that you won't get locked out of a world if you join back quick enough.

This is no longer the case and will lock you out of the world until the cache is (manually) cleared.

**Comment by Provini** [comment]
Closing as supposedly fixed from a recent emmVRC update.

**Comment by Provini** [comment]
Reopening as the occur still happens from time to time.

**Comment by thetrueyoshifan** [comment]
This is most likely caused by lag or other delay causing the game to close before properly dropping you from an instance. A check is needed to see if you are still in the instance before initiating a proper restart
