### ISSUE TITLE
Overlapping volume and emm buttons

### ISSUE THREAD

**Issue by UlmStephen** [emmVRC/emmVRC-Public#1313]
![image](https://user-images.githubusercontent.com/39814033/101957577-ae17da80-3bcf-11eb-81bd-0799bf71055b.png)

**Comment by rakosi2** [comment]
We are aware of this issue since the Beta build. We should have a patch to roll out for it soon. 
MultiplayerDynamicBones's button is also going to need to move.

**Comment by thetrueyoshifan** [comment]
Will be fixed in emmVRC 2.4.1
