### ISSUE TITLE
[Bug]Avatar Parameter Ints are saved as random values.

### ISSUE THREAD

**Issue by rakosi2** [emmVRC/emmVRC-Public#1316]
emmVRC is saving all avatar Ints as random values in the billions, plus-minus. All floats values are saved properly. I know that my ToggleMarker should not be close to the value -422157221. All previously saved avatar ints still loads properly and there is only an issue saving the int values.

**Comment by thetrueyoshifan** [comment]
Fixed with emmVRC 2.4.0
