### ISSUE TITLE
[Bug] Permanent drop in FPS due to emmVRC's Favorite Avatars row.

### ISSUE THREAD

**Issue by KiwasoVR** [emmVRC/emmVRC-Public#1317]
emmVRC Favorite List continues to render even though the menu has been closed. This generates a large permanent FPS loss depending on the favorite avatars you have.
For example, I have 113 favorite avatars and I lose between 20 and 30 fps on Desktop. (114 fps to 80)

When you start VRChat, the game runs at its maximum FPS. But when you open the Avatars menu this problem occurs and it affects even if you close the menu.

In emmVRC> Settings we can Disable emmVRC Favorite List, this returns our FPS, but if we activate it they go back down.

Solution: Stop rendering this row of favorite avatars when the VRChat menu remains closed.

**Comment by thetrueyoshifan** [comment]
This should be fixed as of 2.4.0. Let me know if it is still an issue!
