### ISSUE TITLE
[BUG REPORT] Avatar searches with special characters does not work and yields no search.

### ISSUE THREAD

**Issue by RetroZX0** [emmVRC/emmVRC-Public#1319]
When searching for avatars by a user with special characters in their name, Emmm does not yield a search.

For example, this is what normally happens when you search a user via the "Search Avatar" button on a users detail page via the emmm functions.
![image](https://user-images.githubusercontent.com/76197831/102581382-4a9d1980-40b5-11eb-9b90-13cf491db96c.png)

This is what occurs when you search a user via the text input that contains special characters. (i.e. "ᴢᴀᴘᴘᴀ") [Note that searching via the "Search Avatars" button in the user detail page yields the same result.
![image](https://user-images.githubusercontent.com/76197831/102581426-66a0bb00-40b5-11eb-860a-5032ffac373b.png)

This is not to be confused with zero search results, as seen here.
![image](https://user-images.githubusercontent.com/76197831/102581462-7d471200-40b5-11eb-8372-da5d8fce0e11.png)

I believe this is a bug, and would like to see it resolved. I have gotten access to this creators avatars through vanilla means and have verified that they are in the emmm network as seen here (Femboy maid 1, 2, & 3). 
![image](https://user-images.githubusercontent.com/76197831/102581651-d9aa3180-40b5-11eb-852b-3df8324ebb16.png)

**Comment by rakosi2** [comment]
EmmVRC skips all standard ASCII characters including language-specific characters like Japanese.

**Comment by thetrueyoshifan** [comment]
This is an issue with our current implementation of the search. Avatar searching currently only supports standard ASCII, and this is intentional. While we would like to support unicode and special characters, it's a lower priority as we do reworking of the network

**Comment by thetrueyoshifan** [comment]
This should no longer be an issue
