### ISSUE TITLE
[Bug Report] Radial menu fails in various ways when used on both hands

### ISSUE THREAD

**Issue by knah** [emmVRC/emmVRC-Public#1326]
There are various failure modes to it - clicking things on one hand adding items to the menu on other hand, clicking things on one hand entering the menu on other hand (requiring multiple "back" clicks to get out), some cases lead to empty menu, and so on.
![20201224022913_1](https://user-images.githubusercontent.com/4705494/103089018-fa5e1400-45ec-11eb-97c6-29f6ba519ca2.jpg)

**Comment by gompocp** [comment]
I'm not sure if I'm helping here but I encountered this as well when making my mods, I came up with something like this for it https://github.com/gompocp/ActionMenuRespawn/blob/main/ActionMenuApi.cs#L243

**Comment by thetrueyoshifan** [comment]
This should have been fixed with an older version of emmVRC, let me know if it's still an issue
