### ISSUE TITLE
[Feature Request/bug]

### ISSUE THREAD

**Issue by AngryMadRageFace** [emmVRC/emmVRC-Public#1328]
is it possible to have customizable keybinds for each feature or menu for quicker access?

**Comment by rakosi2** [comment]
EmmVRC already has customizable keybinds for several Features. You can find it in the last page of emmVRC's settings.

**Comment by Provini** [comment]
As rak said, this is already a feature of emmVRC. 
![image](https://user-images.githubusercontent.com/71570801/103327857-6349ef80-4a24-11eb-8574-a5ea1f98a24e.png)

**Comment by AngryMadRageFace** [comment]
i mean for EVERY function
