### ISSUE TITLE
[BUG] Avatar search results incorrectly labels all avatars as quest compatible

### ISSUE THREAD

**Issue by AngryMadRageFace** [emmVRC/emmVRC-Public#1331]
literally ALL avatars found on the avatar search engine are listed by default as quest compatible, AND they are listed just the same way when favorited under the EMMVRC favorites bar. When they are favorited under the normal favorites bar, they are listed with the correct compatibility. I found this out for numerous avatars that I have shuffled between the two bars which turned out to be solely PC compatible under the normal one, but quest compatible under the modded one

**Comment by rakosi2** [comment]
This is a known issue #6 closing.
