### ISSUE TITLE
[Bug] Custom Menu Music only changes on VRChat reload.

### ISSUE THREAD

**Issue by MaxAdventures** [emmVRC/emmVRC-Public#1335]
The new feature Custom Menu Music works, but it picks the songs in alphabetical order instead of random and that means you are only going here one song no matter what unless you move every other song out and just have one so what I'm saying is fix the code, so it does it random and not alphabetically.

**Comment by Janni9009** [comment]
It does actually pick the file randomly, however i think there may be a little bug in the code the way i read it, causing at least the last two songs to never be played,

**Comment by MaxAdventures** [comment]
dam ok i just might be unlucky

**Comment by MaxAdventures** [comment]
> It does actually pick the file randomly, however i think there may be a little bug in the code the way i read it, causing at least the last two songs to never be played,

Ok but there is a bug where once you have loaded in to the game, and it has played a song. It will stay to that song the hole time, and it will not change at all. When you go into a new world same song. You have to restart to get a new song.

**Comment by thetrueyoshifan** [comment]
It is intentional that the same song plays throughout the game being started. However, the randomization not picking the last two songs is not intentional

**Comment by thetrueyoshifan** [comment]
Fixed with emmVRC 2.6.6
