### ISSUE TITLE
[Bug] Social UserInfoPage Playlist button game object misbehaving

### ISSUE THREAD

**Issue by KortyBoi** [emmVRC/emmVRC-Public#1337]
Although a smaller, non-Game-breaking, bug, I still thought I'd let someone know.<br>
emmVRC Functions button hiding Playlists button incorrectly some times. GIF shows everything (below)
https://kortyboi.com/img/upload/UrtiPJ6v70.gif

**Comment by KortyBoi** [comment]
![GIF](https://kortyboi.com/img/upload/UrtiPJ6v70.gif)

**Comment by rakosi2** [comment]
I have also noticed emm's buttons visible when the tab is collapsed.

**Comment by thetrueyoshifan** [comment]
I so far have not been able to reproduce this. Are you using any other mods that might potentially interact with that space?
