### ISSUE TITLE
Avatar search crash

### ISSUE THREAD

**Issue by GamingGavin** [emmVRC/emmVRC-Public#1338]
I have tested this multiple times and even had a friend try it and it keeps happing. If you use the search function for avatars in emm and search for IA it wont search for it. Then if you try a few times it freezes your game and makes you manually restart the game.

**Comment by loukylor** [comment]
May I ask what you're trying to search with EMM? If you search something that would be in a lot of avatars (for example just "a") that results in thousands of avatars it could crash your game.

**Comment by GamingGavin** [comment]
I tried looking for the vocaloid "IA"

**Comment by rakosi2** [comment]
Similar to ticket #81

**Comment by thetrueyoshifan** [comment]
This is caused by multiple searches being done at the same time; with IA, there are currently 9231 results in our database. This should be fixed with the next version of emmVRC.
