### ISSUE TITLE
[FEATURE] A limit on how many avatars are shown in the search

### ISSUE THREAD

**Issue by loukylor** [emmVRC/emmVRC-Public#1339]
I'm sure this has been considered before, but I'd like to suggest this just in case. It's as the name suggests, add a limit to how many avatars the list will show when searching for avatars. As for the number shown in the search list, it might be good to tell the user both the original number and the number it has been limited to.

Also, it would be nice if there could be an override for this in the settings somewhere or a setting in the config that lets you change this limit.

**Comment by thetrueyoshifan** [comment]
This will be added in the next emmVRC update
