### ISSUE TITLE
[FEATURE] avatar creator search

### ISSUE THREAD

**Issue by VoxOnDiscord** [emmVRC/emmVRC-Public#1346]
have a way to find avatars made by someone by going to their profile and clicking a button of sorts if possible

**Comment by rakosi2** [comment]
If you click on someone then there is a button to Search Avatars. It will just put their username in our avatar search box. also just the one creator has already been asked #1306 
![image](https://user-images.githubusercontent.com/6037087/104363027-74d1d380-54c9-11eb-88c1-6226c43220d5.png)
