### ISSUE TITLE
[Feature Request] Original Trust Ranks

### ISSUE THREAD

**Issue by NataIynn** [emmVRC/emmVRC-Public#1347]
Could we have the ability the ability to see old ranks back? I would like to see people with legendary, veterans.

**Comment by rakosi2** [comment]
The mod [OGTrustRanks](https://github.com/HerpDerpinstine/OGTrustRanks) will bring back the Veteran and Legendary Trust Ranks. You can find other verified mods here at https://discord.gg/rCqKSvR> in #finished-mods once you accepted the rules.

**Comment by NataIynn** [comment]
That mod is out dated.

**Comment by Provini** [comment]
The mod is up to date and works perfectly fine.

**Comment by NataIynn** [comment]
The creator said its not up to date. It's 3 months out of date from all the VRC Updates. There is a known issue on the mod itself which is what I'm having.

**Comment by rakosi2** [comment]
The latest version is 1.0.7 and it still works. What is the issue that you are having?

**Comment by NataIynn** [comment]
https://github.com/HerpDerpinstine/OGTrustRanks/issues/8

**Comment by Provini** [comment]
OGTrustRanks won't show you as legendary to others. It only shows who's legendary to yourself. The only way these ranks are even visible is with the mod. The rank will also be hidden as normal of they are Appearing as User.

**Comment by NataIynn** [comment]
Weird, even though other mod clients that are private can see what rank I am legendary (pink name). But all my friends who use OGTrustRank sees I'm trusted. I also see myself as trusted, but in VRCX shows I'm legendary.  Yes I'm using the mod, and yes ALL them are using the mod.

![image](https://user-images.githubusercontent.com/28743579/104919633-2d7d9400-595c-11eb-833b-689573f754b2.png)
![image](https://user-images.githubusercontent.com/28743579/104919738-5867e800-595c-11eb-9d29-a8d4d79fb58e.png)

**Comment by thetrueyoshifan** [comment]
No longer possible with the recent removal of legacy ranking information from the API
