### ISSUE TITLE
Some Mods Breaking with EMM

### ISSUE THREAD

**Issue by Grobitalks** [emmVRC/emmVRC-Public#1349]
Hey could u make "sendRequest" a ienumerator or a normal void, i think that will fix a lot of issues

**Comment by rakosi2** [comment]
What mod is emmVRC having issues with?

**Comment by Grobitalks** [comment]
Any mods using threading it seems. so far in my testing

**Comment by rakosi2** [comment]
Could you drag and drop your latest MelonLoader log file here? You can find it in VRChat\Logs.

**Comment by Grobitalks** [comment]
![unknown](https://user-images.githubusercontent.com/77458170/104631099-0db84880-569c-11eb-8b38-1669083c4523.png)

**Comment by Grobitalks** [comment]
that is a success login, when with a mod using threading

**Comment by rakosi2** [comment]
that doesn't really tell me much, can you upload your full log from VRChat\Logs.

**Comment by Grobitalks** [comment]
Could you join a server i am basically a middleman here henceforth i cant really send the logs since mine are unrelated. 
Could u join a discord and talk to Krewella they figured this out and know all the info.

**Comment by rakosi2** [comment]
Our discord is https://discord.gg/emmvrc or VRCMG's https://discord.gg/rCqKSvR

**Comment by Grobitalks** [comment]
Add Plague#2850 and they will explain the bug on discord

**Comment by Grobitalks** [comment]
Please just forward this thanks :)

**Comment by thetrueyoshifan** [comment]
Our networking uses C# asynchronous tasks, because we are using the .NET networking for communications with the emmVRC Network. I do want to rewrite the stack, and that is in the works, but I also think the problem lies elsewhere.

**Comment by thetrueyoshifan** [comment]
Closing this for now, as the network rewrite is on the to-do list, but we have a lot of other things to do first.
