### ISSUE TITLE
[Feature Request] Video player hider

### ISSUE THREAD

**Issue by TechnoWolf2** [emmVRC/emmVRC-Public#1352]
I often crash when loading any video player, so if there were a way to locally hide them or unload them before they load the video, that would be perfect.

**Comment by Inktrinket** [comment]
I could see this helping VRChat users with low PC specs.

**Comment by KortyBoi** [comment]
You can use the mod [ComponentToggle](https://github.com/KortyBoi/ComponentToggle) to toggle various things across worlds

**Comment by thetrueyoshifan** [comment]
Available as of several emmVRC versions ago
