### ISSUE TITLE
[bug] button to open emmvrc menu has been overridden by User Icons VRC+

### ISSUE THREAD

**Issue by AngryMadRageFace** [emmVRC/emmVRC-Public#1353]
I moved the menu button over to the left where its closer to my mouse cursor, and it wasn't a problem before, but now its disappeared entirely. I cannot access anything but avatars and risky functions. Also I am not sure how you are supposed to disable buttons because apparently there is a section for those.

I think their should be an emergency factory default key press for all menu settings

**Comment by rakosi2** [comment]
To disable Stealth Mode, click the Report World button in your quick menu. From there, you can access emmVRC Functions. You'll find the Stealth Mode toggle in Settings.

**Comment by rakosi2** [comment]
If the button needs to be moved then you can with this [image](https://img.thetrueyoshifan.com/Coordinates.png)

**Comment by rakosi2** [comment]
Reopen if you are still having issues

**Comment by AngryMadRageFace** [comment]
I dont recall actually turning on stealth mode but apparently that happened :P
