### ISSUE TITLE
[Feature Request] Disabling the Idle Animation.

### ISSUE THREAD

**Issue by HannahYasuko** [emmVRC/emmVRC-Public#1354]
Basically the most recent update has broken my way of using TTS. Before the most recent VRC Update; if you had the VRC Menu tab open (worlds, avatars, friends or settings), it would stop your character from going into the sitting position (idle animation). Every time I use my TTS to speak; I have to go to Oculus Dashboard and use virtual desktop to type. So I am wondering if it's possible to disable the idle sitting animation/any idle animation while I am exited into the Oculus Dashboard. Now if you were to press the menu button on your controller while in the VRC Settings menu; it will put you into an idle pose. I still want to be able to move my hands around freely with the hand gestures enabled while tabbed into Oculus Dashboard. Hopefully you can understand what I am trying to say; just explaining it as best as I can. Thanks!

**Comment by RiskiVR** [comment]
You can fix this natively in VRChat. Simply open the action menu, go to config, Disable AFK Detection.
