### ISSUE TITLE
[Bug] Closing Avatar Search

### ISSUE THREAD

**Issue by rakosi2** [emmVRC/emmVRC-Public#1355]
Closing the avatar menu will not close the avatar search like it used to. You currently need the refresh button to bring back the emmVRC Favorites. emmVRC v2.6.1

**Comment by TechnoWolf2** [comment]
Honestly, I like this better, keeping the search open. But I get it would be annoying for some, what would be better is set a button in emm function settings where you could have it keep the search or not.

**Comment by thetrueyoshifan** [comment]
This is actually an implementation change, as this fixed aonther bug where search would be closed when scrolling down in the list. At the moment, there are no plans to change this behavior,
