### ISSUE TITLE
[bug] avatar creator search

### ISSUE THREAD

**Issue by VoxOnDiscord** [emmVRC/emmVRC-Public#1358]
with some people I search their avatars and i only see like 8 out of the hundreds they have made, I would like if this feature was more refined if at all possible as it is quite frustrating when the avatar is something you don't know the name of and the creator doesn't show it.

**Comment by rakosi2** [comment]
emmVRC will only search from the database of avatars that other emmVRCs have favorited before, therefore not all avatars are searchable.

**Comment by VoxOnDiscord** [comment]
is this possible to fix? or just how it is?

**Comment by rakosi2** [comment]
VRChat removed the ability to search for all public avatars so it is not possible.

**Comment by thetrueyoshifan** [comment]
It is possible to view the public avatars of a user via the API, but emmVRC operates separately from this. At the moment, this is not something we are looking to fix, but if you favourite the avatars from those creators, they will fill the emmVRC Search results.
