### ISSUE TITLE
[Feature] Add grabbable dynamic bones

### ISSUE THREAD

**Issue by Kyvski** [emmVRC/emmVRC-Public#1359]
Currently, we can only push bones with our hands. It would be nice to have a toggle that enabled us to grab bones and drag them around. This should obviously only be seen by other emmvrc users, like global dynamic bones.

**Comment by thetrueyoshifan** [comment]
This is likely not possible without entirely rewriting how DynamicBones works, as (to my knowledge), it does not support pivoting or moving bones manually. You could potentially use Dynamic Bone Colliders to achieve the same result, using emmVRC's Global Dynamics module. As such, this is out of the scope of emmVRC at this moment.
