### ISSUE TITLE
[Bug] Some keys for the shortcuts are not settable in emmVRC settings

### ISSUE THREAD

**Issue by rakosi2** [emmVRC/emmVRC-Public#1360]
keys that I have noticed missing is all num pads, '=', '`', '[', ']', ';', ''', , Insert, Home, Page up/down, Delete, and End.

**Comment by thetrueyoshifan** [comment]
This is intentional for the time being. We have a whitelist of allowed characters, and those are not allowed to avoid some potential issues.
