### ISSUE TITLE
[Feature] fps limit

### ISSUE THREAD

**Issue by Thatportal** [emmVRC/emmVRC-Public#1361]
remove vr fps limit and set it to 72 like what the actual game has,

**Comment by BLANKE1** [comment]
I believe the FPS limit is set by SteamVR or Oculus (whichever client you play on)

**Comment by Thatportal** [comment]
when ever i have emmvrc my fps is at 36 but when i remove emmvrc out of my game my fps goes to 72

**Comment by BLANKE1** [comment]
That's most likely not a limit. Try disabling the emmVRC netork and global dynamic bones. Does it still happen?

**Comment by RiskiVR** [comment]
There is no FPS limit, you're most likely dropping frames because of Global Dynamic Bones.

**Comment by Thatportal** [comment]
i turned global dynamic bones off and network off but its still fighting to 36 fps

**Comment by RiskiVR** [comment]
Your PC might not be powerful enough to run VRChat with modifications. What are your specs?

**Comment by Thatportal** [comment]
radeon rx580 and the cpu is a ryzen 5 2600 with 48 gb ram

**Comment by RiskiVR** [comment]
you should be fine, otherwise your VRChat might be capped by something else

**Comment by BLANKE1** [comment]
Do you have any other mods than emmVRC?

**Comment by Thatportal** [comment]
ya but i loaded emm by it self and its not capped it is another mod

**Comment by BLANKE1** [comment]
could you tell us your other mods? or just send your melonloader log with you running the game with the mods you use

**Comment by Thatportal** [comment]
im trying to see which mod it is

**Comment by Thatportal** [comment]
my findings are surprising every time i open a mirror it drops my fps by half it doesnt matter how many mirrors i turn on

**Comment by Thatportal** [comment]
it also matters on how many people are in the lobby

**Comment by Thatportal** [comment]
but i think there is a mod too but im lazy

**Comment by BLANKE1** [comment]
Is it low quality mirrors or high quality mirrors? does that matter

**Comment by rakosi2** [comment]
emmVRC has a feature to force all mirrors to Optimize in the world tweaks, could you try that.

**Comment by Thatportal** [comment]
it doesnt work on limit

**Comment by thetrueyoshifan** [comment]
This is not a feature of emmVRC, and is most likely related to an issue with your configuration. Please ask in the Discord, available at:
https://ttyf.me/emmvrcd

I'm going to close this, as it's not a bug or feature
