### ISSUE TITLE
Social List/Friends List split in different pages (like the favourites list) to fix the lag of loading much profiles

### ISSUE THREAD

**Issue by Progamer75303** [emmVRC/emmVRC-Public#1362]
Please make this pages (by the avatars so it dont lags) also by the social list. I have mostly 200 online friends and it lags me very much. If I want to invite somebody its so laggy because it is loading the whole online friends list. And please also do it by the offline list. PS if it isnt possible no problem its just a tiny request which just would be a nice thing to have. Thx keep up your good work ;)

**Comment by thetrueyoshifan** [comment]
At the moment, it's not possible to modify other lists with this feature, as emmVRC manually manages all the items placed into a paginated list, whereas VRChat handles its' own lists.
