### ISSUE TITLE
it no longer works

### ISSUE THREAD

**Issue by mangle99vvg13** [emmVRC/emmVRC-Public#1365]
I don't know much English but emmvrc no longer works, no emmvrc window appears, what happened?

**Comment by rakosi2** [comment]
We are working on pushing an update for emmVRC. In the meantime you can update/reinstall MelonLoader to 0.3.0
![image](https://user-images.githubusercontent.com/6037087/106666974-24481600-655d-11eb-965e-251dc5936a78.png)
