### ISSUE TITLE
[Bug] Custom NamePlate Color

### ISSUE THREAD

**Issue by NataIynn** [emmVRC/emmVRC-Public#1367]
This feature use to work correctly, before the new name plates was introduced. This been broken ever since.  Player names changes correctly, but the gray nameplate box doesn't change.

![image](https://user-images.githubusercontent.com/28743579/106679402-338d8a80-6582-11eb-9f23-e34014580be3.png)

**Comment by KortyBoi** [comment]
You can use [BTKNameplateFix](https://github.com/ddakebono/BTKSANameplateFix) to color your nameplates.
