### ISSUE TITLE
user menu overlapping with emms functions  

### ISSUE THREAD

**Issue by kingleaf2555652** [emmVRC/emmVRC-Public#1368]
everything overlapps 
![SharedScreenshot](https://user-images.githubusercontent.com/78454272/106680918-0e4e4b80-6585-11eb-9397-79616f7f0038.jpg)

**Comment by rakosi2** [comment]
Only happens when emmVRC Actions is clicked on, the only way to close is by closing menu

**Comment by thetrueyoshifan** [comment]
Fixed with emmVRC 2.6.6
