### ISSUE TITLE
FEATURE REQUEST- to See what Platform Some avatars are On

### ISSUE THREAD

**Issue by BettyGlitchFell** [emmVRC/emmVRC-Public#1372]
i hang out with Friends that good bit are Using Normal Quest and Quest2 and they ask me to look for avatars for them and im happy to do so but it would Help more if i can see what Platform its on because i feel bad when i find it and its on PC and they cant use it because they cant Afroed a PC that can Run VR

**Comment by rakosi2** [comment]
We are aware of this issue and working on it with the Network rewrite #6 sorry about that.
