### ISSUE TITLE
[Feature] setting to make clock 12 hour format

### ISSUE THREAD

**Issue by markviews** [emmVRC/emmVRC-Public#1373]
Clock used to be 12 hour format but is 24 hour format now.. A setting to change it back would be cool

**Comment by Provini** [comment]
One thing to note is that it's supposed to reflect the time setting on your PC. The fact that it doesn't is actually a bug.

**Comment by thetrueyoshifan** [comment]
This bug should be fixed, and the clock should reflect the time setting instead in emmVRC 2.7.0
