### ISSUE TITLE
[BUG REPORT] Attempting to recover from corrupt config.json when config.json.old exists throws ERROR_ALREADY_EXISTS and fails to fix the corrupted config.json

### ISSUE THREAD

**Issue by jlitewski** [emmVRC/emmVRC-Public#1374]
I was trying to figure out why emm wasn't working, and I dug through the logs and found that my config.json file was corrupted, and it was throwing an error trying to overwrite the config.json.old file.

Now, I don't know a lot of c#, but I do know that this feels like there isn't any sort of check to see if the file exists _before_ trying to overwrite it.

**STEPS TO REPRODUCE**
1.) Create a config.json.old file in `%VRCHAT_INSTALL_DIR%/UserData/emmVRC`
2.) FUBAR the config.json file
3.) Try to run VRChat

**WHAT SHOULD HAPPEN**
Emm sees that the `config.json` file is invalid, and begins the process of recovering from it. In doing so, emm sees that `config.json.old` is also in the directory, so it creates a new file called `config.json.<date>_<time>.old`. Emm then creates a fresh config.json file and continues to load

**WHAT ACTUALLY HAPPENS**
Emm sees that the `config.json` file is invalid, and begins to recover from it. Emm tries to write `config.old.json` but it already exists, which throws an unchecked exception causing  OnApplicationStart to end prematurely, which never fixes `config.json`. When Emm reads the config.json file, it gets garbage and causes the app to fail to start.

**FILES**
[MelonLoader log](https://github.com/emmVRC/emmVRC-Public/files/5929803/MelonLoader_21-02-03_23-19-18.234.log)

**Comment by thetrueyoshifan** [comment]
Fixed with emmVRC 2.6.8
