### ISSUE TITLE
[Bug] emmVRC Favorites flicker

### ISSUE THREAD

**Issue by rakosi2** [emmVRC/emmVRC-Public#1377]
emmVRC Favorites flickers and there are no errors in the log. Also happens with only emmVRC loaded. Happens in VR too.

video: https://cdn.discordapp.com/attachments/807109298982354955/807344272146825256/2021-02-05_15-17-08.mp4
conversation: https://discord.com/channels/600298024425619456/807109298982354955/807329306375225385

**Comment by thetrueyoshifan** [comment]
This, as far as I know, is a VRChat issue. It seems to happen most frequently with large lists, and it also happens in the Social Menu.
