### ISSUE TITLE
[BUG] quick menu hud toggles back on if hidden and you toggle normal hud with ctrl + h

### ISSUE THREAD

**Issue by Tracenji** [emmVRC/emmVRC-Public#1378]
if you toggle quick menu hud with ctrl + J to off and then toggle VRC hud with ctrl + H then it toggles quick menu hud back on (and the other way around)

does not happen with the toggle hud button under UI elements in the quick menu

**Comment by thetrueyoshifan** [comment]
Will be fixed in emmVRC 2.7.0
