### ISSUE TITLE
[BUG] Instant Restart is Non-Functional

### ISSUE THREAD

**Issue by loukylor** [emmVRC/emmVRC-Public#1381]
The instant restart button simply force closes the game; in its current state it is basically another force quit button.

**Comment by rakosi2** [comment]
Instant Restart worked for me with all working mods running. Do you have any broken mods installed?

**Comment by loukylor** [comment]
I just tested with only emm installed. it doesn't seem like a conflicting mod issue.
Here's my log just to prove that it is the only mod:
[Latest.log](https://github.com/emmVRC/emmVRC-Public/files/5937796/Latest.log)

**Comment by thetrueyoshifan** [comment]
I'm having trouble understanding why it stops working in the first place. It seems to be completely random, and for random people. Is your VRChat.exe named differently, or something along those lines?

**Comment by loukylor** [comment]
No, my VRChat exe is not renamed. I know that KortyBoi has a working one in his mod. Perhaps you could ask him?

**Comment by thetrueyoshifan** [comment]
Are you using QuitFix? emmVRC initiates “OnApplicationQuit” to ensure you are removed from the instance before quitting, but it may close the game immediately as well

**Comment by loukylor** [comment]
Ah yea, I'm using QuitFix. So removing the launch option would fix the issue?

**Comment by thetrueyoshifan** [comment]
It should. QuitFix takes precedence over emmVRC's Force Quit and Instant Restart, and prevents it from functioning how it should.
