### ISSUE TITLE
Emmvrc doesn't work on vrc cause of this error message

### ISSUE THREAD

**Issue by lilstavo** [emmVRC/emmVRC-Public#1382]
![Screenshot (2)](https://user-images.githubusercontent.com/52061587/107132369-2bd82980-6893-11eb-8f3d-95e52857ba33.png)

**Comment by Hordini** [comment]
Hello! Please post your latest MelonLoader log file in the emmVRC Discord server. If you need help locating it, please ask us there.
Here is an invite link if you need it: https://discord.gg/emmvrc
