### ISSUE TITLE
Just doesn't work.. Help?

### ISSUE THREAD

**Issue by LinksterDinkster** [emmVRC/emmVRC-Public#1383]
Reinstalled MelonLoader and the emmvrc.dll and it still doesn't work. 
![emmvrc](https://user-images.githubusercontent.com/78719489/107182970-a76cd000-6992-11eb-8f97-fecaa637779c.PNG)

**Comment by rakosi2** [comment]
You need to install MelonLoader 0.3.0 by enabling alpha builds in the installer's settings

**Comment by LinksterDinkster** [comment]
> You need to install MelonLoader 0.3.0 by enabling alpha builds in the installer's settings

Thank you!!!!
