### ISSUE TITLE
[Feature Request] Force Clone

### ISSUE THREAD

**Issue by Itz-Y2** [emmVRC/emmVRC-Public#1385]
I have been trying to find a free Force Clone for Vrc and can't find one, if the EMM team or someone link me a dll for one that would be nice.

https://user-images.githubusercontent.com/78839783/107469533-84c3ee00-6b2f-11eb-9bcd-da03c659c09b.mp4

**Comment by loukylor** [comment]
Please read the rules in the Discord as force cloning is against emmVRC's rules.

**Comment by Hordini** [comment]
We will not be adding this as a feature. Please refer to our Feature Blacklist here: https://github.com/emmVRC/emmVRC-Public/issues/7
