### ISSUE TITLE
[Feature Request] Unicode in Avatar search

### ISSUE THREAD

**Issue by DeeFourCee** [emmVRC/emmVRC-Public#1386]
I would like to request that unicode be applied to avatar search. 

Currently if an avatar name or author does not contain English characters it does not appear and if you search author’s avatars using the drop down menu in their social page and they have non-english characters the search just fails and throws and error that the search wasn’t possible. 

Thus I would like to request that this be fixed as it will give us access to many more public avatars namely those from asian creators.

**Comment by rakosi2** [comment]
Dup of #1319 . While we would like to support unicode and special characters, it's a lower priority as we do reworking of the network
