### ISSUE TITLE
[BUG] Random crashing

### ISSUE THREAD

**Issue by N4IL** [emmVRC/emmVRC-Public#1393]
Recently many people with emmVRC installed have been reporting random crashing in the Help and support channels with no indication of something being wrong in their Latest.log file according to the Lum bot, and I have not had the issue first hand to attempt at recreating or attempting solutions.

**Comment by thetrueyoshifan** [comment]
This should be somewhat improved with emmVRC v.2.7.3. We're still doing some testing to figure out any more potential crashes.

**Comment by thetrueyoshifan** [comment]
Closing this issue for now. If random crashes are still happening, let me know and I’ll open it back up
