### ISSUE TITLE
[BUG] emmVRC Not Working on Oculus Version

### ISSUE THREAD

**Issue by Blair-Witch** [emmVRC/emmVRC-Public#1396]
Previous to the last vrc and melon updates, Emma had always worked for me while using the Oculus App version of VRChat. However, as of the last updates, emm loads and connects to the network, but my emm favorites list does not appear along with the avatar search being grey and unusable. I have attempted to reinstall everything from emm to melon to VRC to the whole oculus app, and nothing has worked.

**Comment by Provini** [comment]
This is currently a known issue. You can view the #known-bugs channel in our Discord server to see it's current status. (Currently labeled as broken.)

**Comment by thetrueyoshifan** [comment]
Should be fixed in emmVRC v2.7.4
