### ISSUE TITLE
[Bug] Unable to select avatars in the "Other" category

### ISSUE THREAD

**Issue by advanced4** [emmVRC/emmVRC-Public#1400]
This new tool promoted by the official VRChat twitter account (https://readyplayer.me/blog/custom-vrchat-3d-avatar-maker-creator) can automatically create an avatar for you.

It puts the avatar in the "other" category. EMM flags the avatar as private, and will not allow you to change to it. However, if I remove the mod, and restart VRC, I can change to the avatar as intended

**Comment by thetrueyoshifan** [comment]
Fixed in emmVRC 2.7.4
