### ISSUE TITLE
[Feature Request] Free camera movement mode

### ISSUE THREAD

**Issue by HannahYasuko** [emmVRC/emmVRC-Public#1403]
A toggleable option to unlink the camera from your body. While enabled; you can use your mouse and keyboard/controllers to move the camera around. Camera can travel through walls. Camera speed is same as the player's walkspeed. Player's body will be put into a default pose/freeze in the last pose they were in before activating freecam. Player's body will not move until deactivated. I got this idea when I glitched my camera through a wall and it kept travelling way behind where I was standing, which froze my character in place.

**Comment by HannahYasuko** [comment]
- [ ]

**Comment by KortyBoi** [comment]
This can be used for potential malicious intent, like spying on people in private rooms or gaining an unfair (top-down view) advantage in some game worlds.
