### ISSUE TITLE
[Feature] Music player in world

### ISSUE THREAD

**Issue by N4IL** [emmVRC/emmVRC-Public#1410]
Hello, I would like the option to play music that I have imported into emm while in a world instead of just at the loading screens.

**Comment by N4IL** [comment]
Probably not too good of a title, but whatever.

**Comment by BLANKE1** [comment]
You could use spotify/youtube and use the Media function keys

**Comment by loukylor** [comment]
emm already has music controls, so I don't really see the point in this.

**Comment by KortyBoi** [comment]
You can play your .mp3, .wav, .ogg file with Windows Media Center, VLC, or Groove (Windows 10 Default Music App). Then you can use emmVRC's media control keys to change songs.
