### ISSUE TITLE
emmVRC stopped working

### ISSUE THREAD

**Issue by FBIHansen** [emmVRC/emmVRC-Public#1412]
emmVRC takes longer to load, and once you get into the game it doesn't work

**Comment by BLANKE1** [comment]
One of melonloader's API is down and please follow the issue format aswell

**Comment by KortyBoi** [comment]
This issue should be fixed now. Make sure you have MelonLoader on the latest v0.3.0 _Alpha_. If you need help updating or reinstalling MelonLoader, please do so in our [Discord Server](https://discord.gg/emmvrc)
