### ISSUE TITLE
↕ Feature ↕ opitmizer for lag when have many tabs

### ISSUE THREAD

**Issue by elvistrejo** [emmVRC/emmVRC-Public#1413]
works beter when laging hard

**Comment by elvistrejo** [comment]
install any time

**Comment by loukylor** [comment]
Please describe your issue more. Currently this is very vague. Also, try to keep a more professional tone, i.e. spelling, capitalization phrasing, etc.

**Comment by elvistrejo** [comment]
hosted by etrejo_03

**Comment by elvistrejo** [comment]
have little experience bar for adjust ment
definitely be less lagy when playing hard map or avarts

**Comment by elvistrejo** [comment]
when press the menu button side bar

**Comment by elvistrejo** [comment]
comes up

**Comment by elvistrejo** [comment]
on the side

**Comment by elvistrejo** [comment]
but in the fution tab

**Comment by elvistrejo** [comment]
ready for bug testing

**Comment by elvistrejo** [comment]
![image](https://user-images.githubusercontent.com/46251292/110723163-40cd1300-81d9-11eb-88ad-5289900f07e3.png)
![image](https://user-images.githubusercontent.com/46251292/110723197-4a567b00-81d9-11eb-9cf4-5953bdab8442.png)

**Comment by elvistrejo** [comment]
just like that

**Comment by rakosi2** [comment]
So you want us to limit VRChat's RAM And CPU usage?

**Comment by elvistrejo** [comment]
yes but only in the tab that use

**Comment by elvistrejo** [comment]
when done make shore it work good before send to public

**Comment by nitrog0d** [comment]
what is your main language?

**Comment by elvistrejo** [comment]
English

**Comment by BLANKE1** [comment]
"when have many tabs" just close your browser or don't have many tabs open and have tab discipline idk what else to say.

**Comment by BLANKE1** [comment]
Locking the Ram of a game would use would probably cause a lot of issues. You could process lasso or advanced systemcare to trim the memory.

**Comment by elvistrejo** [comment]
When your a progamer you may lots tab runing  in background

**Comment by elvistrejo** [comment]
Well i want to test it out on my computer just only that i use that that if good them i will back recording level from 1 to 10

**Comment by BLANKE1** [comment]
Limiting the Ram of a game won't help the performance of the game. It would most likely make it worse as it doesn't have headroom.

**Comment by elvistrejo** [comment]
Ok it when i the future its going to get lagy very hard

**Comment by BLANKE1** [comment]
That's on VRChat's part. Like I said you can use Advanced SystemCare or Process Lasso to garbage collect useless ram that VRChat is using.

**Comment by elvistrejo** [comment]
Ok

**Comment by elvistrejo** [comment]
Well someone close the thred
