### ISSUE TITLE
[Feature] Block more malicious entries from avatar search

### ISSUE THREAD

**Issue by BLANKE1** [emmVRC/emmVRC-Public#1414]
Widen the blacklisted search terms like "Crash, Crasher, Clapper, common vrchat "gangs", the n word, ect" and remove avatars with those terms off the database to prevent users to access public crashers. This gives more people access to malicious crashers and is mostly the biggest cause of people having crasher avatars in the first place, Having them removed from the emmVRC database and having it more moderated would make VRChat a lot more safe.

**Comment by BLANKE1** [comment]
Also have existing emmVRC favorites that are crasher avatars removed from people's lists would also be a good addition as well.

**Comment by thetrueyoshifan** [comment]
This is not feasible, due to the high potential of false positives.
