### ISSUE TITLE
[FEATURE] Disable pickups

### ISSUE THREAD

**Issue by NinjaKid90** [emmVRC/emmVRC-Public#1415]
Allow us to have to option to disable pickups for worlds that don't allow them by default, i.e. Great Pug. This would be great in the same tab where Disable Chairs and Disable Portals are. Might be great for lower spec PCs.

**Comment by Flapppyy** [comment]
Yep thats true, that update would be nice for me

**Comment by KortyBoi** [comment]
You can use the mod [ComponentToggle](https://github.com/KortyBoi/ComponentToggle) to toggle various things across worlds

**Comment by thetrueyoshifan** [comment]
Added as a feature in emmVRC v2.8.0
