### ISSUE TITLE
Ability to check avatar creator on self

### ISSUE THREAD

**Issue by milkx2** [emmVRC/emmVRC-Public#1416]
i always found my self having to ask friends who made my avatar, and having to ask them how the name is spelled (vise versa). Something that would let us check our own avatar authors could be a pretty helpful idea with the avatar search menu.

**Comment by Hordini** [comment]
Hello,

This is already possible using our current features. Go to emmVRC Functions > Player Tweaks > Select Current User. From there, you can select Show Avatar Author on yourself.
