### ISSUE TITLE
[BUG REPORT] the time doesn't reflect the format used on pc, my pc is set to 24 hour, emm uses 12hr, and changing to 12hr and back doesn't fix this

### ISSUE THREAD

**Issue by charlie59876** [emmVRC/emmVRC-Public#1418]

**Comment by loukylor** [comment]
There is a toggle for this in emm's settings.

**Comment by thetrueyoshifan** [comment]
A fix is in the pipeline for the next version of emmVRC that will read the actual set status, rather than using your country’s default format.
