### ISSUE TITLE
Mod Compatibility - MultiplayerDynamicBones

### ISSUE THREAD

**Issue by Dervali-git** [emmVRC/emmVRC-Public#1419]
emmVRC had a compatibility module that would disabled Global Dynamic Bones when Multiplayer Dynamic Bones (MDB) was present in order to avoid conflicts between the two mods. However that has stopped working due to some changes with MDB. 

I recently took over maintaining a fork of MDB and in doing so changed the mod name slightly to differentiate it from the original mod. I believe this broke the compatibility check that emmVRC was doing.  The currently published version of MDB on the VRCMG discord is https://github.com/Dervali-git/MultiplayerDynamicBonesMod

I'm not sure how emmVRC was doing the check, but I assume it was checking the mod name, which changed from 'Multiplayer Dynamic Bones' to 'MultiplayerDynamicBonesMod'

I just tested this myself on VRC 1062 and with the most recent version of emmVRC installed, along with MultiplayerDynamicBonesMod, the Global Dynamic Bones option added colliders to bones.

**Comment by thetrueyoshifan** [comment]
This is correct. emmVRC references the ModInfo classes of all the mods loaded by MelonLoader to determine what is loaded. I have a fix for this in the pipeline, and it should come out soon!

**Comment by kevdevrev** [comment]
Can you please renable the option to use EMMVRC global dynamic bones if MDB is off, because I much prefer using the EMMVRC version as it is more performant in public worlds, but I like to use MDB when I am in private worlds.

**Comment by Dervali-git** [comment]
Maybe a togglable preference in emmVRC to disable the compatibility check for MDB? Or if there is some way our two mods could check if the either has that specific feature enabled in the other one? 

@kevdevrev Not to clutter this issue, but would you be able to open an issue [here](https://github.com/Dervali-git/MultiplayerDynamicBonesMod/issues) on the performance difference, or message me on Discord Nirvash#0001 to discus reproduction steps for the performance difference? Assuming the same filtering is applied in both mods, there shouldn't be much of one

**Comment by kevdevrev** [comment]
Dervali reached out and I solved my performance issues with MDB.

**Comment by Hordini** [comment]
This issue was corrected in emmVRC v2.7.8
