### ISSUE TITLE
[Error] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by Kayrosis** [emmVRC/emmVRC-Public#1420]
I got this error on the first time loading.

[MelonLoader_21-03-15_19-09-29.194.log](https://github.com/emmVRC/emmVRC-Public/files/6145204/MelonLoader_21-03-15_19-09-29.194.log)

**Comment by N4IL** [comment]
Please go to #help and support in the discord server for help

**Comment by rakosi2** [comment]
Please reinstall/update MelonLoader alpha 0.3.0  https://github.com/LavaGang/MelonLoader.Installer/releases/latest/download/MelonLoader.Installer.exe
https://media.discordapp.net/attachments/807109298982354955/810352859539439646/geuCSLseKf.gif
