### ISSUE TITLE
[Bug] EULA pop-up instantly closes after it appears

### ISSUE THREAD

**Issue by Provini** [emmVRC/emmVRC-Public#1421]
This causes you to not able to click "Open EULA" or "Agree" as it instantly closes, allowing a user to use emmVRC without agreeing to the EULA.

This causes the EULA pop-up to happen every time the game is launched.

**Comment by thetrueyoshifan** [comment]
I have not been able to reproduce this issue. Are you using any other mods with emmVRC, and are you on Oculus or Steam?

**Comment by Provini** [comment]
Seems to have randomly resolved itself or was silently fixed.
