### ISSUE TITLE
Playlisting [Feature Request}

### ISSUE THREAD

**Issue by ARlTITAN** [emmVRC/emmVRC-Public#1426]
a ability to add world/avatar playlists, each one being nameable would be nice but no really needed. simply place it as organization for favorited stuff

**Comment by BLANKE1** [comment]
You can do this kind of thing with FavCat

**Comment by KortyBoi** [comment]
Yes [FavCat](https://GitHub.com/knah/VRCMods) allows you to add extra World Favourites, User Favorites, and Avatar Favorites, all unlimited, all with pretty much as much custom categories as you'd like.
