### ISSUE TITLE
[BUG REPORT] VRChat Update(2021.1.5) Breaks Full Body Tracking if Using emmVRC

### ISSUE THREAD

**Issue by Arikx** [emmVRC/emmVRC-Public#1427]
Hello All,

Some of you may know that VRChat just released an update, and with that update you're had your avatar "crumble" after calibrating. After re-installing my game, it works fine on vanilla.

The moment you install emmVRC, it will no longer work. It seems like VRChat Team found a way to "expose" or rather make it difficult for people to use mods for VRChat.

Replicate Steps:

1. Update VRChat.
2. Launch VRChat with FBT on.
3. Calibrate yourself.

Steps to resolve(Not a workaround to work with emmVRC)
1. Re-Install the game - OR - remove emmVRC and Melon Loader.

TODO: Determine if it's the fault of Melon Loader or emmVRC(I have to go do errands...)

Proof by Tupper that they're acknowledging the FBT issue is a result of using a modified client.
![image](https://user-images.githubusercontent.com/28694575/112238655-15074f80-8c13-11eb-85bb-8b2b978859af.png)

**Comment by BLANKE1** [comment]
Known issue check the discord. Fixed by disabling calibration saving.

**Comment by BLANKE1** [comment]
emmVRC functions>Settings>Calibration Saving. If you don't know where that's at

**Comment by Arikx** [comment]
> Known issue check the discord. Fixed by disabling calibration saving.

Thank you so much, I haven't joined Discord yet but will join! I've been out of the loop.

**Comment by KortyBoi** [comment]
We will be fixing this ASAP. Thank you for your patience.
