### ISSUE TITLE
[Feature] Ask me my pin every x day so i can remember it

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [emmVRC/emmVRC-Public#1443]
Hi, i got this idea because i'm seeing a lot of people forget their pin. 
The inspiration came from the Signal app, the app ask you every 7 says your recovery pin.
So i was thinking of something like this for emmvrc, maybe not every 7 day but once a month, and if you fail to get it emm ask's you to set a new pin

Just a small feature for people who are a bit absent-minded like me :)
Have a great day

**Comment by KortyBoi** [comment]
You can always just create a text file, put it on your desktop, and put your pin in that. That way you always have it.

**Comment by Deathcaw200** [comment]
I also forgot my pin because I did knew the pin but like few months I forgot it now I don't know to keep forget the pin
