### ISSUE TITLE
Favorites list not loading

### ISSUE THREAD

**Issue by whinejamin** [emmVRC/emmVRC-Public#1453]
My favorites list is failing to load It says to check my internet connection and thats all it says. when i look at the main menu the menu states i am connected to the emmvrc network but the list wont load i have attached some pictures to show the issue 
![error log](https://user-images.githubusercontent.com/82688054/115097985-06027d00-9ef3-11eb-87a5-4bcf69070e28.PNG)
![connected](https://user-images.githubusercontent.com/82688054/115098038-5f6aac00-9ef3-11eb-9a5c-10ae2a964b4a.PNG)
![error](https://user-images.githubusercontent.com/82688054/115098041-62659c80-9ef3-11eb-9919-3b4701d9ee7c.PNG)
please let me know if this is just a error on my end or what

**Comment by Provini** [comment]
The network is currently down. Please be patient as we resolve this issue. In the future use the #help-and-support channels in the emmVRC Discord for support. https://discord.gg/emmvrc

**Comment by whinejamin** [comment]
thank you for the swift response i hope everything is back up soon
