### ISSUE TITLE
[BUG] emmVRC will not load in at all

### ISSUE THREAD

**Issue by stanvcher** [emmVRC/emmVRC-Public#1458]
![Capture](https://user-images.githubusercontent.com/82998054/115666908-2aa38e00-a313-11eb-8c37-5306107c0db5.JPG)

I dont know what to do, i have uninstalled and installed melonloader and emmvrc and it seems to not change it

**Comment by loukylor** [comment]
The emmVRC Network is currently experiencing heavy load, Network functions may be impacted.

**Comment by stanvcher** [comment]
will it reload itself when theres not a heavy network load?

**Comment by teddyhaku** [comment]
mine is the exact same what does this mean?

**Comment by loukylor** [comment]
> will it reload itself when theres not a heavy network load?

yes

**Comment by loukylor** [comment]
> mine is the exact same what does this mean?

it means the network is down. please be patient until the network is back up.

**Comment by MRK100** [comment]
I have the same problem, and after 8 hours, nothing has changed, so what is the solution?Is there a way to fix this problem?
@loukylor

**Comment by KortyBoi** [comment]
> I have the same problem, and after 8 hours, nothing has changed, so what is the solution?Is there a way to fix this problem?

Read above. This is a know issue and we're trying to fix it. Please be patient. We will announce in our Discord server once things are fixed.
