### ISSUE TITLE
Supporters page comes up with "Network Error"

### ISSUE THREAD

**Issue by rubychaan** [emmVRC/emmVRC-Public#1464]
Not sure if it's just me, however when i go to emmVRC functions then supporters it does not load and has network error at the bottom and has done so for the past day or two.

![image](https://user-images.githubusercontent.com/83148542/115977932-9d389600-a5bf-11eb-9ef9-95ad46b4aa25.png)

**Comment by thetrueyoshifan** [comment]
Fixed as of emmVRC v2.10.0
