### ISSUE TITLE
Black listing a intrustive mod?

### ISSUE THREAD

**Issue by Dias2525** [emmVRC/emmVRC-Public#1469]
Is it possible either in melonloader or emm to have a mod black listed? The mod is literally stealing private information

**Comment by Whanos** [comment]
No. Maybe just.. don't install untrustworthy mods?

**Comment by KortyBoi** [comment]
I second what Whanos said.

**Comment by Dias2525** [comment]
ok thanks , im just trying to find a way to help deal with the ripper store trying to profit off private models through some weird pyramid scheme mod

**Comment by Whanos** [comment]
Not sure what you mean by "pyramid scheme mod", but there isn't anything melonloader or emmvrc could do about it anyway

**Comment by Dias2525** [comment]
basically the mod they have you install rips models in worlds you go to and uploaded the vrca files to them and gives your "credits" to "buy" other models they have ripped off their store
