### ISSUE TITLE
[Feature Request] Disable Parameter Sync on Properties with suffix _NoSync

### ISSUE THREAD

**Issue by UiharuKazari2008** [emmVRC/emmVRC-Public#1470]
Can you please allow some avatar parameters to be ignored for sync with a prefix like _NoSync

I need to use a parameter to push a animation time sync but I don't what it sync trough world joins

Maybe better if there were 2 types, one suffix for per restart and one for world change.

**Comment by BenjaminZehowlt** [comment]
This is too niche of a feature to be implemented into emmVRC
