### ISSUE TITLE
[bug] emm stops working after toggling the HUD off/on

### ISSUE THREAD

**Issue by camilafx** [emmVRC/emmVRC-Public#1471]
after turning off the HUD with ctrl+h all emmVRC shortcuts (third person and flying, for example) stop working.

Easy to replicate, here is my log-
[Latest.log](https://github.com/emmVRC/emmVRC-Public/files/6497233/Latest.log)

**Comment by thetrueyoshifan** [comment]
This should be fixed as of a few versions ago
