### ISSUE TITLE
[bug] Can't use "Other" avatars

### ISSUE THREAD

**Issue by Kribaker** [emmVRC/emmVRC-Public#1473]
So I noticed one of the avatars I made in Tafi suddenly started being called by emm as "no longer available" even though I could still use it on Quest. Thinking something may have happened to it, I made another self avatar using readyplayer.me, but that one's doing the same thing. Both of them are under the "Other" category as you can see in the picture.

![image](https://user-images.githubusercontent.com/62083518/118739651-99d7a980-b80f-11eb-83e9-3b407208b044.png)

**Comment by thetrueyoshifan** [comment]
Fixed as of emmVRC v2.9.0
