### ISSUE TITLE
[Feature Request] Just Make it Offline

### ISSUE THREAD

**Issue by DSquared02** [emmVRC/emmVRC-Public#1474]
EmmVRC used to not be on a server and users could install it like they could any other mod. It was a drag and drop mod. It would save the devs money and make users happier.

**Comment by Hordini** [comment]
emmVRC does not rely on our server always being available anymore as of the last few emmVRCLoader updates. We store a local version of the mod in `VRChat\Dependencies`. A connection is only needed in the even that emmVRC updates, or to download emmVRC for the first time.

**Comment by RinLovesYou** [comment]
This actually raises another question i have that would sorta relate to this

Are favorites still only stored on the network? 
If yes: great! thank you!
if no: have you considered local backups of favorites/just moving to local storage?
