### ISSUE TITLE
no puedo buscar avatares

### ISSUE THREAD

**Issue by Valentinamangle** [emmVRC/emmVRC-Public#1485]
no me deja guardar mas avatares, que debo hacer?

**Comment by KortyBoi** [comment]
Lea los anuncios en el servidor de discordia emmVRC. Explica todo lo que necesita saber sobre su "problema".
Server: https://discord.gg/emmvrc
Link: https://discord.com/channels/600298024425619456/600366663426113764/844409133759463426

> no me deja guardar mas avatares, que debo hacer? => It won't let me save more avatars, what should I do?
