### ISSUE TITLE
[Bug Report] 2 menu merge together

### ISSUE THREAD

**Issue by Ohmuzero** [emmVRC/emmVRC-Public#1492]
when I open emm menu then click other people the menu will merge together and floating when close then keeps apearing when open again
![VirtualDesktop Android-20210607-090836](https://user-images.githubusercontent.com/71583222/121116208-5980af80-c840-11eb-9767-e68eb4b6e1e2.jpg)
![VirtualDesktop Android-20210607-090845](https://user-images.githubusercontent.com/71583222/121116213-5b4a7300-c840-11eb-869a-f004f74b822a.jpg)

**Comment by Hordini** [comment]
Thank you for your report, this will be fixed next update.

**Comment by thetrueyoshifan** [comment]
Fixed with emmVRC 2.10.0
