### ISSUE TITLE
Avatar search

### ISSUE THREAD

**Issue by ThatAnimeBoii** [emmVRC/emmVRC-Public#1499]
The avatar search cannot find some public non-malicious avatars that are currently being used in my world by multiple people. I don't know if this is something on my end, theirs, or on the mod's.

**Comment by N4IL** [comment]
That is most likely because they have not favorited to an emm avatar favorites list, for that is the only way that they are added to the emm avatar database.

**Comment by ThatAnimeBoii** [comment]
Okay, thanks.
