### ISSUE TITLE
[Bug] emmVRC Actions button does not function

### ISSUE THREAD

**Issue by Provini** [emmVRC/emmVRC-Public#1503]
`[emmVRCLoader] [ERROR] Unable to find field "currentPage" in QuickMenu`

**Comment by rakosi2** [comment]
Try pushing the UIElements button in the menu.

**Comment by MintLily** [comment]
Opening the UI Elements Menu, sometimes the Emote Menu, before pressing the button you are pressing, will fix your issue. This is an error inside the RubyButtonAPI.

**Comment by thetrueyoshifan** [comment]
Should be fixed in emmVRC v2.10.2
