### ISSUE TITLE
[Feature request] Performance boost function such as render distance of maybe some kind of fog? Or other as you can think.

### ISSUE THREAD

**Issue by Ohmuzero** [emmVRC/emmVRC-Public#1504]

**Comment by loukylor** [comment]
This is an awfully vague description. There is no way to simply just "boot performance". 

Even reducing the far clip plane (which is the same as reducing render distance) wouldn't help much, as it would only stop rendering, which would improve GPU performance, but this is often not the limiting factor for VRChat players. Adding to this, any physics calculations such as dynamic bones or collision would still run. These calculations are done on the CPU, and are often the limiting factor of players. There is also the issue of immersion. Fog works well in horror games, where having a claustrophobic sort of view creates good atmosphere, but in games like VRChat would just make it awkward, especially in VR. On top of this, it would have to be world specific, as reducing the render distance in places like the Legend of Zelda world, where it is extremely open, would be limiting. 

If you would like some type of optimization mod, then mods like AvatarHider and Turbones exist. You can find them in the VRChat Modding Group Discord server. The invite is posted in the partners channel of the emmVRC Discord.
