### ISSUE TITLE
[BUG] Unable to add New EmmVRC Favorites

### ISSUE THREAD

**Issue by Danny-Sevvy** [emmVRC/emmVRC-Public#1509]
After updating melonloader (v0.4.0) and emmVRC (v1.4.0) I am no longer able to add any new avatars to my EmmVRC favorites menu. Instead when I click the button a pop-up that reads "VRChat Plus Required | VRChat, like emmVRC, relies on the support of their users to keep the platform free. Please support VRChat to unlock these features." 

I am still able to use the avatar search and access all my previous 75 saved avatars and favorite avatars with the normal feature (limited to 25 without VRC+, or only 100 with it). I am not sure exactly why vrchat is detecting emmVRC and disabling this feature. 

I've asked a couple people it does seem to be affecting them (they have the same versions of the mod and modloader as me), although with a small sample size I do not know if its a widespread/common issue or something more specific. 

Attached is a screenshot showing that popup menu. I am more than willing to provide more information on my game files, etc.
![image](https://user-images.githubusercontent.com/71983407/124173338-e9e59500-da78-11eb-992a-2ae971e412e4.png)

**Comment by Afootpluto** [comment]
Not a bug, you need VRC+ to add favorites.

**Comment by A-plou** [comment]
it's a new feature on emmVRC, you need VRC+ to add more favorite even with emmVRC now

**Comment by Danny-Sevvy** [comment]
That’s unfortunate. Thanks for letting me know, glad I favorited those avatars before the original feature was removed.
