### ISSUE TITLE
[BUG REPORT] Misinformative Camera Plus hint in settings

### ISSUE THREAD

**Issue by NCPlyn** [emmVRC/emmVRC-Public#1512]
As in title, on hover of Camera Plus button in emmVRC settings, hint of "Local Info Spoofing" is shown instead.

![image](https://user-images.githubusercontent.com/44117369/124798527-bb255e00-df53-11eb-8c29-6b866c02c1d1.png)

**Comment by MintLily** [comment]
Ah yes, the power of copy and pasting a button and forgetting to replace the text.
_hehe_, this will be fixed in the next update.

**Comment by thetrueyoshifan** [comment]
Fixed in emmVRC v2.11.1
