### ISSUE TITLE
[Bug?] Unnecessary out of RAM

### ISSUE THREAD

**Issue by Lupsoris** [emmVRC/emmVRC-Public#1515]
Hello!

I've already contacted support in #help-and-support on your Discord or the VRCMG. It didn't help.

I currently have 12GB of RAM, which has always been sufficient for the game. And I didn't get this bug from an update. So my RAM isn't a problem.
In any case, I have a cloud computer (Shadow), so my RAM changes physically every time I reboot, and I can't do anything to increase it.. I've been playing VRChat for more than a year, and I've never had any problems.

I would also like to point out that even though your Discord bot that allows you to analyze the logs tells me that some mods are corrupted, this isn't true. I already tried to re-download them from the official link, and it didn't change anything.

I prefer to write this introduction so that you don't just say: "Increase your RAM, I can't do anything, goodbye", as in #help-and-support. ^^'

---

The problem as such: as soon as I use EmmVRC and as soon as I go to an instance with people (more people = faster the bug will happen), after a few minutes or even seconds, my RAM fills up to 100% until the game crashes after a few minutes.
Whereas if I play without mods, or with all my mods except EmmVRC, I'm constantly at 6GB total usage, and I have no problems.

I tried to:
- Run the command here: https://help.vrchat.com/hc/en-us/articles/1500002247921-I-crashed-can-t-launch-VRChat-other-issues
- Delete all files of VRChat in SteamLibrary (except "Mods", "Plugins" and "UserData" folders)
- Delete my cache manually
- Delete all files in %appdata%/../LocalLow/VRChat (except my Config.json)
- Check the integrity of the game files in Steam so that the game reinstalls, and run it once
- Reinstall ML 0.4.1 (https://github.com/LavaGang/MelonLoader/releases/tag/v0.4.1)
- Redownload EmmVRC (https://dl.emmvrc.com/downloads/emmVRCLoader.dll)

If I think it's a bug, it's mainly because the game starts to freeze, and only **then** my RAM starts to fill up.

I have attached my last log with all my mods (including EmmVRC) with ML 0.4.1, a log with EmmVRC only (ML 0.4.0) as well as a log with EmmVRC only and "--melonloader.debug".

Thank you,
`Lupsoris#0001`

[Latest_All_Mods.log](https://github.com/emmVRC/emmVRC-Public/files/6796901/Latest_All_Mods.log)
[EmmAlone.log](https://github.com/emmVRC/emmVRC-Public/files/6796907/EmmAlone.log)
[EmmAlone_Debug.log](https://github.com/emmVRC/emmVRC-Public/files/6796908/EmmAlone_Debug.log)

**Comment by Provini** [comment]
Are you using Local Info Spoofing/Hiding? There's an issue where it may cause this.

**Comment by Lupsoris** [comment]
Normally, no.
Here's my Emm config file.

[config.txt](https://github.com/emmVRC/emmVRC-Public/files/6797640/config.txt)

**Comment by Provini** [comment]
Does the problem persist if you reset emmVRC to defaults? (By backing up and/or deleting the config somewhere.)

**Comment by Lupsoris** [comment]
> Does the problem persist if you reset emmVRC to defaults? (By backing up and/or deleting the config somewhere.)

I already tried to delete everything in UserData > EmmVRC, except the Config.json.
Should I try to delete everything in the EmmVRC folder?
There are no other folders/files created by EmmVRC except in UserData?

**Comment by Lupsoris** [comment]
I actually noticed that if I deleted my config, I didn't crash.
But as soon as I set back my initial configuration (not the file but doing it manually in the EmmVRC menus), I was crashing again.
I tested and it seems that I crash if I activate the Risky Function. Not sure and to check.

**Comment by Lupsoris** [comment]
Okay, that's pretty weird. So far everything works even with the Risky Function.
I'll come back in a few days to close the post if I don't see any more problems. ^^

**Comment by Lupsoris** [comment]
Hello, the problem has surely been corrected since then, in one way or another.
I don't have any more problems so I close this issue.
Thanks everyone :)
