### ISSUE TITLE
Weird shader issue

### ISSUE THREAD

**Issue by Brentroe** [emmVRC/emmVRC-Public#1517]
not sure if its emm i just want to fish to see if anyone else has had this issue 
im getting some strange bug, idk if its from a mod but if i stay in a world for too long my mirrors break and become black and if the world has post processing it breaks and turns my whole view black

**Comment by rakosi2** [comment]
I know that a panorama photo breaks mirrors without any mods since April but it turns white, not black. Kind of surprised that is still an issue. Could you upload your VRChat/MelonLoader/Latest.log here or in our discord https://discord.gg/emmvrc
