### ISSUE TITLE
[BUG] Risky functions not working

### ISSUE THREAD

**Issue by AnthonyAlonzo** [emmVRC/emmVRC-Public#1519]
It says risky functions is not enabled even though I have it enabled in the settings
![VirtualDesktop Android-20210713-185213](https://user-images.githubusercontent.com/43357807/125535316-b2e2be3b-9e4b-4f79-9da5-315b63ed2a53.jpg)
![VirtualDesktop Android-20210713-185227](https://user-images.githubusercontent.com/43357807/125535317-22d1b02f-785e-4781-844b-15ada90df0bf.jpg)

**Comment by thetrueyoshifan** [comment]
Hi, are you still experiencing this issue?
