### ISSUE TITLE
[FEATURE] not running emmVRC to VRC bulid 1116

### ISSUE THREAD

**Issue by tjaudry30** [emmVRC/emmVRC-Public#1523]
not running emmVRC to VRC bulid 1116..
so quick Update plz

**Comment by loukylor** [comment]
Beta versions of VRChat are not supported by emm, nor are they supported by almost all mods. Please downgrade VRChat for emm to work.

**Comment by Hordini** [comment]
As mentioned above, Beta versions of VRChat are usually not supported by most mods including emmVRC. The Open Beta however has allowed us to prepare an update for the launch of 1116, which will be released soon after 1116 is pushed to release.
