### ISSUE TITLE
Error message after mods load 

### ISSUE THREAD

**Issue by PuppyHugs21** [emmVRC/emmVRC-Public#1529]
It loads the mods, but then an error appears after. I'm not sure what to do. Here's the latest log. I really hope someone can help

[MelonLoader_21-08-04_17-14-00.385.log](https://github.com/emmVRC/emmVRC-Public/files/6935085/MelonLoader_21-08-04_17-14-00.385.log)

**Comment by Janni9009** [comment]
The game had a major update. Please wait until emmVRC is updated as well.

**Comment by PuppyHugs21** [comment]
makes sense. I had a feeling this was probably the case but I wasn't sure.
Thanks for the quick response
