### ISSUE TITLE
[BUG] Avatar Search not working

### ISSUE THREAD

**Issue by Euzoia** [emmVRC/emmVRC-Public#1532]
So when I load into my vrchat, I tried to click search in the avatar tab, but it doesnt do anything or so its not even clickable. I also notice that where the avatars would usually load, its not even there anymore. I don’t know if the emmvrc is messed up. After I updated the emmvrc too, I think thats when it started or maybe not, I’m just clueless on what im doing wrong.

**Comment by loukylor** [comment]
Can you check if you are connected to the emm network?

**Comment by Euzoia** [comment]
> Can you check if you are connected to the emm network?

For some reason, I try to enter a pin, but it asks me to enter a pin again, so I don’t know.

**Comment by loukylor** [comment]
Go into the emm discord at discord.gg/emmvrc, then in the network support channel, ask for a pin reset.

**Comment by Euzoia** [comment]
> Go into the emm discord at discord.gg/emmvrc, then in the network support channel, ask for a pin reset.

Oh ok!! Thank youu
