### ISSUE TITLE
emmvrc issue

### ISSUE THREAD

**Issue by TruKane** [emmVRC/emmVRC-Public#1534]
![Captureemmvrc](https://user-images.githubusercontent.com/66936128/128616876-31f3bfea-c2ba-4595-9688-d12d3ae9a6cb.PNG)

This happens every time I try to launch with emmvrc, I've used emmvrc before but the new vrchat update kinda broke a lot of mods so I uninstalled everything and everything went well until I launched vrchat and it said it could not be loaded.

**Comment by loukylor** [comment]
Do you have any launch options? Specifically the `--emmvrc.devmode` launch option.

**Comment by TruKane** [comment]
> Do you have any launch options? Specifically the `--emmvrc.devmode` launch option.

yeah I do

**Comment by loukylor** [comment]
That prevents emm from downloading the core of itself. Emm is trying to load the core, but cant find the file. To fix your issue simply remove the argument.
