### ISSUE TITLE
trouble with MelonLoader

### ISSUE THREAD

**Issue by WitheringAway** [emmVRC/emmVRC-Public#1535]
Hi, my vrc username changes everytime i log on or restart my vr, i know emm is the cause and ive uninstalled it and reinstalled but i still get the repeated code of.

Setting breakpad minidump AppID = 438100
Steam_SEtMinidumpSteamID:  Caching Steam ID:  [removed] [API loaded no]
Unable to read VR Path Registry From C:\Users\[removed]\AppData\Local\openvr\openvrpaths.vrpath

please help me.

**Comment by N4IL** [comment]
Hello, what I think is likely happening to cause the name change is that you have emm's local info spoofing frature enabled in emm functions --> settings, and for future reference, please use the help and support channels in the emmvrc discord server.

**Comment by Janni9009** [comment]
The first half of the console output snippet you posted is normal (and actually generated by the game or SteamVR). And the openvrpaths file error might actually be OpenVR Input Emulator looking at some past cases of it. (uninstall this if you do have it, it's outdated and broken).
As @N4IL said, you likely have local info hiding/spoofing enabled in your emmVRC settings.
Also, please be careful when posting snippets of the raw console output, they might contain personal data (like your steam ID and Windows Username, as I "[removed]" here. Log files would omit these.
