### ISSUE TITLE
Errors about no API and the game won't launch.

### ISSUE THREAD

**Issue by Gofastestguy** [emmVRC/emmVRC-Public#1538]
Never even touched the files, worked fine yesterday and today I keep getting errors ive never gotten before. The game never launches. 

Here's my logs,
[Latest.log](https://github.com/emmVRC/emmVRC-Public/files/6987757/Latest.log)

**Comment by rakosi2** [comment]
Try updating MelonLoader to 0.4.3 For quicker support, join and upload your log in our discord https://discord.gg/emmvrc

**Comment by Gofastestguy** [comment]
That worked! Thank you for helping this poor smooth brain TwT
