### ISSUE TITLE
[Feature] Allow world creators to disallow rejoining an instance from instance history

### ISSUE THREAD

**Issue by FireTik** [emmVRC/emmVRC-Public#1539]
A way to make it so players cant use instance history to rejoin a privately uploaded world? We have one that we use for events and there's ppl rejoining after events, to use the world, and we don't want the world used unless its during an event! and having to remove the world from upload each time in-between events can be a pain.

**Comment by loukylor** [comment]
This isn't really a problem we can use. People visit private worlds for various reasons, some less wholesome than others, but most of the reasons are legitimate, so I cant see a majority of people benefitting from this. There's also a few other ways of getting and saving the world without using a modified client, so even if we did prevent people from using instance history to get into private worlds, they could get around it.
