### ISSUE TITLE
When trying to search an avatar by someones user profile. Nothing will show up

### ISSUE THREAD

**Issue by EffecOwO** [emmVRC/emmVRC-Public#1541]
When i try to search someone avatar that the person is wearing no results show up

**Comment by BLANKE1** [comment]
When you search a user on emmVRC's Avatar Search it searches their **own** public avatar not the avatar their wearing. You can use something like [VRCX](https://github.com/natsumi-sama/VRCX/) or UserInfoExtensions (Mod in the VRC Modding Group) to look at what avatar a person's wearing and you can search that name in the emmVRC search if it's in the database

**Comment by loukylor** [comment]
> You can use something like [VRCX](https://github.com/natsumi-sama/VRCX/) or UserInfoExtensions (Mod in the VRC Modding Group) to look at what avatar a person's wearing

No, this is impossible. The most you can get from VRCX is the thumbnail, and the most you can get from UserInfoExtensions is the author of the avatar. It is literally impossible to grab more information about the avatar a person is wearing from the social page.

**Comment by BLANKE1** [comment]
> > You can use something like [VRCX](https://github.com/natsumi-sama/VRCX/) or UserInfoExtensions (Mod in the VRC Modding Group) to look at what avatar a person's wearing
> 
> No, this is impossible. The most you can get from VRCX is the thumbnail, and the most you can get from UserInfoExtensions is the author of the avatar. It is literally impossible to grab more information about the avatar a person is wearing from the social page.

![image](https://user-images.githubusercontent.com/68296465/131228104-d85c55ae-1c76-45fd-845a-77f48bd6c83b.png)

VRCX can get Avatar Names Public Or Private
