### ISSUE TITLE
[Feature] Clone an avatar via URL

### ISSUE THREAD

**Issue by imagitama** [emmVRC/emmVRC-Public#1544]
# Idea

Right now there is no way to clone an avatar using a URL (a link from a browser for example). But it works for worlds:

```
vrchat://launch?ref=vrchat.com&id=wrld_1b3b3259-0a1f-4311-984e-826abab6f481:59086
```

Adding support for avatar URLs would be useful if you want to share a publically clonable avatar from social media/Discord/etc.

I suggest adding this to emmVRC as I assume it is possible because you can do the same with worlds.

# How it could be done

The feature already works for worlds.  The client would need to add a protocol handler in Windows to intercept any URL for VRChat avatars - exactly like VRChat already does for worlds:

```
vrchat://launch?ref=vrchat.com&avatarId=avtr_fb4095c1-6ac9-463b-b387-80434a7efa73
```

Then the client would just clone the provided avatar ID just like it normally does (there is already an API endpoint for it).

# Comments

This feels like a really easy and quick win for the community. I created the website VRCArena and being able to clone an avatar with 1 button click would be REALLY cool.

**Comment by loukylor** [comment]
You can already do this with VRCX. 

Direct access -> Avatar -> Enter the avatar ID -> clikc the 3 dots thing -> clone avatar.

If this were implimented in emmVRC I'm pretty sure it would need to be a separate program and have elavated (admin) permissions. Similar to VRChat's install.exe This presents a latge number of issues when trying to convince people that emmVRC isn't a virus.

If I'm wrong feel free to correct me.

**Comment by imagitama** [comment]
> You can already do this with VRCX.

Why not have it in this mod too?

As for the elevated permission thing that makes sense. I guess having an avatar ID input with a paste button would be *something*
