### ISSUE TITLE
Cant click anything first time opening

### ISSUE THREAD

**Issue by DramaticHugs** [emmVRC/emmVRC-Public#1546]
once you install it then you cant click any of the settings at all until you close the game and reopen it
it might have just been me since im completely new to this

**Comment by loukylor** [comment]
Can you clarify what settings are? The emmVRC settings? VRChat settings? Or perhaps you mean things like player tweaks.

Also a log and a screenshot of the nonfunctional buttons would be avery appreciated.

**Comment by DramaticHugs** [comment]
i mean the emmVRC setting sorry! they work now that i restarted vrchat btw
i have circled the broken buttons in light blue
![VRChat_1920x1080_2021-09-11_17-34-26 899_LI](https://user-images.githubusercontent.com/90468676/132953257-5e7ad47c-df95-4fd2-8327-f2a0f1bf4d36.jpg)

**Comment by rakosi2** [comment]
Try pushing the UI Elements before the emmVRC Fuctions. Sounds like #1503 is back.

**Comment by DramaticHugs** [comment]
dont worry it works now, it just required a restart. I still wanted to point it out because i thought it might be worth pointing out

**Comment by loukylor** [comment]
> Try pushing the UI Elements before the emmVRC Functions. Sounds like #1503 is back.

It's a reproducible issue. It is fixed in 3.0.0
