### ISSUE TITLE
[Feature] Head Collider

### ISSUE THREAD

**Issue by Blizzball** [emmVRC/emmVRC-Public#1549]
I would like for there to be a feature that functions similar to hand and feet colliders.  However, if it interacted with the user’s dynamic bones, it would interfere with things like tongue and nose dynamic bones.  I would like to be able to boop people’s ears and they move, and the head bone would be the best place to attach these.  I’d like it to be toggleable just like the hand and feet colliders, but it shouldn’t interact with the user’s dynamic bones.

More concise: head collider that works like hand and foot colliders, can interact with other people’s dynamic bones, but can not interact with the users dynamic bones.

**Comment by loukylor** [comment]
You seem to misunderstand how dynamic bones work.

They're added on by *avatar creators* not emmVRC. What emmVRC does, is make the colliders and bones collide with the colliders and bones on other people's avatar (thus the name *global* dynamic bones). So, if you had say hand colliders turned off in emmVRC, it would make the hand colliders not collide with the bones and colliders on other avatar.

 So, if you'd like this, you'd have to have whoever makes the avatars you use add it for you.

**Comment by Blizzball** [comment]
No I understand.  I’d like to able to put a collider on my head bone in
unity.  I would like emm to allow that collider to interact with other
people.

**Comment by Blizzball** [comment]
I guess the non interaction with your own bones would be something I’d have to do in Unity.  My brain wasn’t working properly, I’d like to just have a global head colliders option!  Sorry for the confusion!

**Comment by Blizzball** [comment]
I’ll close the issue and make a more concise one.
