### ISSUE TITLE
[Feature] Desktop and VR platform indicators

### ISSUE THREAD

**Issue by Github-User-632345** [emmVRC/emmVRC-Public#1552]
Instead of showing "PC" for both VR and Desktop how about a 3rd icon for "VR" and "PC" only show when on desktop?
it's already in the VRChat API and its normal information sent out and recieved from the game so why not add indication for desktop mode.

**Comment by loukylor** [comment]
This is not true. The property you are likely talking about is the `last_platform` property on users. This property has one of two states:
- `standalonewindows`
- `android`

It is not possible to tell whether a user is in VR just using the VRChat API.

**Comment by Janni9009** [comment]
It's a part of the VRCPlayerApi class, an SDK component limited to players in the same instance as you. Not a part of the actual web api. Best possible result would be a nameplate indicator, but at that point you probably know by their movement.
