### ISSUE TITLE
RECONNECT button

### ISSUE THREAD

**Issue by AngryMadRageFace** [emmVRC/emmVRC-Public#1566]
Vrchat has a habit of crashing, losing connection, timing out, etcetera. We need a button that forces it to reconnect to the servers.

**Comment by loukylor** [comment]
Reconnect to the servers? Which servers? If VRChat's then pressing the only available button when you disconnect will reconnect you. If emmVRC's then, well, emmVRC automatically tries connecting if it gets disconnected.
