### ISSUE TITLE
Help me - emmVRC Failed

### ISSUE THREAD

**Issue by NoxOffWhite** [emmVRC/emmVRC-Public#1569]
Hello, 

I got that bug everytime, someone know why?
![Capture d’écran 2021-11-08 213541](https://user-images.githubusercontent.com/93959563/140851583-f875a18d-3b5e-499f-b1c9-ac4d879ed280.png)

Thanks

**Comment by rakosi2** [comment]
Please download the VRChat Mod Updater and move it into your Plugins folder: https://github.com/Slaynash/VRCModUpdater/releases/latest/download/VRCModUpdater.Loader.dll

**Comment by NoxOffWhite** [comment]
> Please download the VRChat Mod Updater and move it into your Plugins folder: https://github.com/Slaynash/VRCModUpdater/releases/latest/download/VRCModUpdater.Loader.dll

Thank you for your answer, but I still got an error message :/

![Capture d’écran 2021-11-09 145403](https://user-images.githubusercontent.com/93959563/140995170-75c5b83c-6b89-4ab7-8f0f-39ac2a920592.png)
