### ISSUE TITLE
[FEATURE] Enable looking around in desktop while menu is open

### ISSUE THREAD

**Issue by g17123** [emmVRC/emmVRC-Public#1572]
The old version of the vrchat menu let you look around in desktop and click on people. The new menu locks your view point which is quite annoying in desktop. You can press shift to hide the menu then do it but this is kind of dumb to be honest and feels like a step backwards. Reverting this would make desktop less annoying again. Heck can even be optional.

**Comment by rakosi2** [comment]
There is a button in the main menu called "Select User" to switch back to the old style of looking around, no mods are needed.
