### ISSUE TITLE
Always Slide Issue

### ISSUE THREAD

**Issue by Wwaveyuwu** [emmVRC/emmVRC-Public#1577]
In the new update, I'm either unaware of where the option for always side is or its unavailable. Just wanted to know if there was a way to enable it because after uninstalling emmVRC and then reinstalling it no longer works.

**Comment by Hordini** [comment]
Assuming you mean "always sliding in full body tracking", this is not provided by emmVRC. Rather it is a feature of IKTweaks. Be sure to update to the latest version 1.0.20, as well as UI Expansion Kit 0.4.0.
