### ISSUE TITLE
Risky Functions menu broken

### ISSUE THREAD

**Issue by BreEzi1** [emmVRC/emmVRC-Public#1579]
So I have been asking about this for awhile and trying to figure it out, for some reason after the recent update to VRchat I cant use the Risky Functions, (or any of the options for that matter).

Don't get me wrong I understand that the new update made it (it being emm) not work with the new UI, but after the emm 1.5.0 .dll came out I replaced the old one, reset and uninstalled/installed melon launcher or the vrmelonassist. I have deleted and thrown out every file and started brand new, I took out my other mods (all of them from GITHUB have been updated for VRchat's new UI software) and just had the emmVRC.dll in there but still nothing. 

Now when Load into game it loads up fine, it "works" and by that I mean I can select things. The issue im having is that when I go into settings to turn on Risky Functions (RF) to fly or something it turns on until I close my menu. In which case it turns itself off right after. No matter what I do to try and keep RF open it refuses to work. 
I have even tried to see if I could use the options in any of the menu that stay on but none of them respond to anything. For example i turned off portals to see if it would stop the use of portals in the world, yes i was owner of the instance, but still it allowed them to be placed. 
 Any ideas?

**Comment by thetrueyoshifan** [comment]
Fixed with emmVRC 3.0.2
