### ISSUE TITLE
[Bug] flight does not stop movement and you will infinitely float

### ISSUE THREAD

**Issue by deerfromvr** [emmVRC/emmVRC-Public#1580]
Using emm flight, when you let go of navigation you will infinitely float in whichever direction you went last as emm is not stopping player movement after letting go of wasd

To recreate this issue:
- turn on emm flight
- jump or move around
- when you try and stop moving you will just float infinitely or until you hit a wall as movement isn't stopped 

Video demonstration:

https://user-images.githubusercontent.com/71858588/140996633-fdf0132b-77fb-44b5-8ecc-8011b084534f.mp4

**Comment by thetrueyoshifan** [comment]
This was partially fixed multiple emmVRC versions ago, although worlds that modify player movement via Udon will likely still exhibit this issue. This is not something we can manage, as it's on a per-world basis, and we recommend using Noclip instead.
