### ISSUE TITLE
Can't change into some public avatars when searching.

### ISSUE THREAD

**Issue by kenway101** [emmVRC/emmVRC-Public#1582]
Some will work and some will not.   Can't even add to favorites.

**Comment by dariendark** [comment]
if you see a message appear on screen advising you you cannot put it on, usually means it has been made private or straight up removed in the case of those who come up as grey bots. sadly with a database the size of emm's, it's not always easy to update the list with every change made by thousands of users every day. so outdated entries are bound to happen.
