### ISSUE TITLE
[FEATURE] Risky feature: avatar size ajustments

### ISSUE THREAD

**Issue by dariendark** [emmVRC/emmVRC-Public#1590]
not sure if this is even possible since the avatars are probably being loaded from a server according to a code we send to other users, but I'm curious if there is a values that can be modified in-game to change the avatar scale. this would be very useful to be able to talk face to face with other players regardless of my chosen avatar's height.

**Comment by Janni9009** [comment]
Not possible indeed, at least not without a specially set-up SDK3 avatar and a mod to fix tracking scaling. Best you can do at the moment is using OVR-AdvancedSettings to playspace move up/down to them.

**Comment by tails101** [comment]
possible, could we integrate scale go brrr
from knah
https://github.com/knah/VRCMods

**Comment by Janni9009** [comment]
This is a nearly year old issue, SGB didn't exist back then.
Also the whole point of having a modloader like MelonLoader is for mods to be modular, leaving no point in us integrating it (at most it just causes conflicts). Just install it as well.
