### ISSUE TITLE
Flying strafe and run speed are reversed/swapped

### ISSUE THREAD

**Issue by Jdbye** [emmVRC/emmVRC-Public#1594]
So just noticed this earlier. Side to side and up/down uses the run speed and forward/backwards uses the strafe speed for VR flying controls. I thought that seemed weird, surely that's a mistake. I checked the desktop controls and there it's correct, forwards/backwards and up/down uses run speed and only side to side uses strafe. Though I would personally prefer if up/down also uses the strafe speed but that's not a big deal. You can always turn the speed up to compensate for the low forward/backward speed but then you have no control when moving up/down or side to side so it doesn't control great.

**Comment by thetrueyoshifan** [comment]
Fixed as of emmVRC v3.0.3
