### ISSUE TITLE
[FEATURE] emmVRC action to send clipboard paste event

### ISSUE THREAD

**Issue by meoiswa** [emmVRC/emmVRC-Public#1598]
As stated on title, adding an action/menu/button somewhere accessible to send a system-wide "ctrl-v" would be incredibly handy for pasting video URLs in video players in VR, amongst other things.

About the "problem":
Using default SteamVR tools available to the user, one can very easily display the desktop environment in VR, open a web browser, navigate to a youtube video (or search for one using the provided virtual keyboard), and copy the URL. However, no built-in tool allows for sending a "paste" command without a context menu, and VRChat does not display one when attempting to right click via the virtual desktop.

How would this help?:
By adding a button one can press directly from some VRChat menu, one could very easily, after selecting a world-space canvas text box (like the one commonly used in video players), send a "ctrl+v" input that would paste whatever was copied before.

**Comment by MintLily** [comment]
There's another mod that does this:
[VRCMG Link](https://discord.com/channels/439093693769711616/854948679915012126/915263549264253069) | [GitHub](https://github.com/meoiswa/VRC-Textbox-Paste)
