### ISSUE TITLE
Console errors on Oculus

### ISSUE THREAD

**Issue by TheCyaniteProject** [emmVRC/emmVRC-Public#1602]
I have had these errors for a few updates but they don't seem to actually cause an problems. Not sure what they are or what they do, but here they are.

> [OVRPlugin][INFO] Initializing system...[OVRPlugin][INFO] OVRInterface plugin library location: C:\Program Files\Oculus\Support\oculus-runtime\client-plugins\x64[OVRPlugin][INFO] OVRInterface plugin libraries:
  Library: C:\Program Files\Oculus\Support\oculus-runtime\client-plugins\x64\XR_EXT_hand_tracking.dll
    Class Id: 0x62582d091582647c, class Name: XrExtHandTrackingExtensionAddition
      Interface Id: 0x4adefbb87b1845cf
    Class Id: 0xed07f75800dea55c, class Name: XrFbHandTrackingAimExtensionAddition
      Interface Id: 0x4adefbb87b1845cf
    Class Id: 0x231a449959b76a41, class Name: XrFbHandTrackingCapsulesExtensionAddition
      Interface Id: 0x4adefbb87b1845cf
    Class[OVRPlugin][INFO] OVRInterface classes and interfaces:
    Class Id: 0x192ed17193ef5e74, class Name: OpenXRExtensionRuntime
      Interface Id: 0x223362abe367d30a
    Class Id: 0x71dee913e4ca6a35, class Name: OpenXRRuntimeHandle
      Interface Id: 0xba2299b1d57a30c7
    Class Id: 0xb00b00067332ab1, class Name: OVRExtensionAddition
      Interface Id: 0xb00b00053345520
    Class Id: 0x2a70ed34760b552e, class Name: ServiceTrexManagerImplementation
      Interface Id: 0xae0b8a9331378a85
    Class Id: 0xaf0a819a96974952, class[OVRPlugin][INFO] LibOVR module is located at C:\Program Files\Oculus\Support\oculus-runtime\LibOVRRT64_1.dll[OVRPlugin][INFO] VkInstanceExtensions:[OVRPlugin][INFO]   VK_KHR_surface[OVRPlugin][INFO]   VK_KHR_external_memory_capabilities[OVRPlugin][INFO]   VK_KHR_win32_surface[OVRPlugin][INFO]   VK_KHR_external_fence_capabilities[OVRPlugin][INFO]   VK_KHR_external_semaphore_capabilities[OVRPlugin][INFO]   VK_KHR_get_physical_device_properties2[OVRPlugin][INFO] VkDeviceExtensions:[OVRPlugin][INFO]   VK_KHR_swapchain[OVRPlugin][INFO]   VK_KHR_external_memory[OVRPlugin][INFO]   VK_KHR_external_memory_win32[OVRPlugin][INFO]   VK_KHR_external_fence[OVRPlugin][INFO]   VK_KHR_external_fence_win32[OVRPlugin][INFO]   VK_KHR_external_semaphore[OVRPlugin][INFO]   VK_KHR_external_semaphore_win32[OVRPlugin][INFO] ProfilerSystem: verbose mode 0[OVRPlugin][INFO] OVRPlugin 1.52.1 ... preinitialized[OVRPlugin][INFO] Initializing system...[OVRPlugin][INFO] OVRInterface plugin library location: C:\Program Files\Oculus\Support\oculus-runtime\client-plugins\x64[OVRPlugin][INFO] OVRInterface plugin libraries:
  Library: C:\Program Files\Oculus\Support\oculus-runtime\client-plugins\x64\XR_EXT_hand_tracking.dll
    Class Id: 0x62582d091582647c, class Name: XrExtHandTrackingExtensionAddition
      Interface Id: 0x4adefbb87b1845cf
    Class Id: 0xed07f75800dea55c, class Name: XrFbHandTrackingAimExtensionAddition
      Interface Id: 0x4adefbb87b1845cf
    Class Id: 0x231a449959b76a41, class Name: XrFbHandTrackingCapsulesExtensionAddition
      Interface Id: 0x4adefbb87b1845cf
    Class[OVRPlugin][INFO] OVRInterface classes and interfaces:
    Class Id: 0x192ed17193ef5e74, class Name: OpenXRExtensionRuntime
      Interface Id: 0x223362abe367d30a
    Class Id: 0x71dee913e4ca6a35, class Name: OpenXRRuntimeHandle
      Interface Id: 0xba2299b1d57a30c7
    Class Id: 0xb00b00067332ab1, class Name: OVRExtensionAddition
      Interface Id: 0xb00b00053345520
    Class Id: 0x2a70ed34760b552e, class Name: ServiceTrexManagerImplementation
      Interface Id: 0xae0b8a9331378a85
    Class Id: 0xaf0a819a96974952, class[OVRPlugin][INFO] LibOVR module is located at C:\Program Files\Oculus\Support\oculus-runtime\LibOVRRT64_1.dll[OVRPlugin][INFO] Connected to the server running version (prod = 1).1.66.0(build = 0) feature version = 0. Client runs version (prod = 1).1.66.0(build = 0) feature version = 0[OVRPlugin][INFO] HMDState::CreateHMDState VsyncToFirstScanline = 0.012020[OVRPlugin][INFO] OVRPlugin 1.52.1 ... initialized[OVRPlugin][INFO] IAD changed to 63.2mm[OVRPlugin][ERROR] Prediction interval too high: 1740.409004 s, clamping at 0.250000 s (<OVR>:0)[OVRPlugin][ERROR] Device required (c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\software\oculussdk\integrations\ovrplugin\main\src\util\compositorcapi_d3d11.cpp:60)[OVRPlugin][INFO] CliD3D11CompositorClient initialized[OVRPlugin][ERROR] OVR Error:
  Code: -1005 -- ovrError_InvalidParameter
  Description: Null IUnknown pointer provided.
  OVRTime: 155845.229996
  Time: 2021-11-20 15:15:06 [392:247:900]
 (<OVR>:0)[OVRPlugin][ERROR] ovr_CreateTextureSwapChainDX failed: Null IUnknown pointer provided.
 (c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\software\oculussdk\integrations\ovrplugin\main\src\util\compositorcapi.cpp:79)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 1 expected 4294967296
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 1 expected 2
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 1 expected 2
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 2 expected 3
 (<OVR>:0)[OVRPlugin][ERROR] ovr_SubmitFrame failed: TextureSwapChain is not valid for layer 0. Make sure ovr_CommitTextureSwapChain has been called.
 (c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\software\oculussdk\integrations\ovrplugin\main\src\util\compositorcapi.cpp:79)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 2 expected 3
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 2 expected 3
 (<OVR>:0)[OVRPlugin][ERROR] ovr_SubmitFrame failed: TextureSwapChain is not valid for layer 0. Make sure ovr_CommitTextureSwapChain has been called.
 (c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\software\oculussdk\integrations\ovrplugin\main\src\util\compositorcapi.cpp:79)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 2 expected 3
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 2 expected 3
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 2 expected 3
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 2 expected 3
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 2 expected 3
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 2 expected 3
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 2 expected 3
 (<OVR>:0)[OVRPlugin][ERROR] ovr_SubmitFrame frameIndex got 1 expected 0
 (<OVR>:0)[OVRPlugin][ERROR] OVR Error:
  Code: -6002 -- ovrError_TextureSwapChainInvalid
  Description: TextureSwapChain is not valid for layer 0. Make sure ovr_CommitTextureSwapChain has been called.
  OVRTime: 155846.412386
  Time: 2021-11-20 15:15:07 [574:637:100]
 (<OVR>:0)[OVRPlugin][ERROR] OVR Error:
  Code: -6002 -- ovrError_TextureSwapChainInvalid
  Description: TextureSwapChain is not valid for layer 0. Make sure ovr_CommitTextureSwapChain has been called.
  OVRTime: 155846.445841
  Time: 2021-11-20 15:15:07 [608:92:300]
 (<OVR>:0)[15:15:08.685] [emmVRCLoader] VRChat build is: 1151
[15:15:09.873] [emmVRCLoader] Initialization is successful in 01.1s. Welcome to emmVRC!
[15:15:09.875] [emmVRCLoader] You are running version 3.0.4
[OVRPlugin][INFO] CliD3D11CompositorClient released[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 22 expected 23
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 22 expected 23
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 22 expected 23
 (<OVR>:0)[OVRPlugin][ERROR] ovr_GetPredictedDisplayTime frameIndex got 23 expected 24
 (<OVR>:0)[requeststopwatch] ovr_PlatformInitializeWindowsAsynchronous took 1.8960 milliseconds
[context] Attempting to re-initialize the platform context, ignoring.
[p2pnetworktransport] oculus_parties_enable_aui_mic_switcher_controls gk is ON, mic_switcher_controls is enabled
Failed to fetch FBNS credentials from OAF: Malformed Oaf response

**Comment by loukylor** [comment]
These look like actual issues with Oculus/Steam (I'm assuming Oculus). The MelonLoader console only picks them up because it's the console for the entire VRChat application. You'll notice they don't have a timestamp prefixed and are all grey. I'm honestly not sure what could cause this, but I would try to reinstall whatever you use to run VR.

**Comment by TheCyaniteProject** [comment]
They were red before the last update and would say something like "Couldn't load player hacks ... OpenXR not found", but I think that was already fixed

**Comment by loukylor** [comment]
The OoenXR not found message happens when you don't have an OpenXR installed or basically if you don't have a VR headset. It is not an error message.
