### ISSUE TITLE
API Doesn't Load

### ISSUE THREAD

**Issue by SpeedBumpJoe** [emmVRC/emmVRC-Public#1605]
Every time i load into VRchat, this is the only line that goes red in the command prompt. emmVRC never loads when I get in-game
![image](https://user-images.githubusercontent.com/92548157/143619463-d59d70a5-3a71-4d7d-a0ec-98a3886f769a.png)

**Comment by loukylor** [comment]
Your MelonLoader installation is missing core files. Please reinstall it.
