### ISSUE TITLE
Cannot Access EMM tab

### ISSUE THREAD

**Issue by Jubarra** [emmVRC/emmVRC-Public#1607]
I'm not sure if it would recreate it, but recently a vrchat update happened, 2021.1.4.2, and when the update occurred I was installing the Avatar Limbs Grabber mod. For some reason, after doing this the update would not occur, whenever I hit update it would nearly finish and then require me to update once more. So I uninstalled the game, reinstalled it, and entered. Afterwards I found that I could no longer access the emm tab, it was still there, but clicking on it would send me to the launch pad. The emm favorites does not show up and I cannot look for avatars, there are also no settings for emm in the mod settings menu despite the log checker claiming it is fine.

**Comment by rakosi2** [comment]
The issue is caused by the Oculus version of VRChat which we are looking into solving.

**Comment by thetrueyoshifan** [comment]
This appears to be working as of emmVRC v3.1.2. If this issue continues to happen, feel free to make a new issue
