### ISSUE TITLE
[BUG REPORT] 3rd person crosshair on head/face

### ISSUE THREAD

**Issue by Hypaholic** [emmVRC/emmVRC-Public#1610]
Going 3rd person the crosshair still shows up on the back of the head and also on the face when using both the 3rd person options, This didn't happen before recent vrchat updates hope there can be a fix for this so i dont need to turn my crosshair off everytime i go 3rd person

**Comment by thetrueyoshifan** [comment]
Fixed in emmVRC v3.1.2
