### ISSUE TITLE
[Feature Request] Enable Support for 10-Point Tracking

### ISSUE THREAD

**Issue by DSquared02** [emmVRC/emmVRC-Public#1618]
I know mods that allowed for more trackers have existed for a while, it would certainly be a LOT of work but as more and more people get ahold of cheaper tracking solutions I believe that we shouldn't leave our old Vive trackers behind. 

What if an option was added to bring the ability to use extra trackers for elbows/knees to EmmVRC as a proper solution to this problem. 10-point tracking is something the devs may never touch due to the small number of people who actually own more than 3 trackers, but other Social VR platforms such as NEOs already offer such functionality. 

Would be cool but the amount of work needed likely won't make this worth developing. In any case it would be a really cool feature. It's been done before so I know it's possible.

**Comment by Janni9009** [comment]
IKTweaks allows this (also grab UIExpansionKit, open the main menu, go to Settings, expand Mod Settings at the bottom right, enable Knee/Elbow/Chest tracker), and provides **much** better IK at the same time. You can get it through [MelonAssistant](https://github.com/knah/VRCMelonAssistant/releases/latest/download/VRCMelonAssistant.exe) or from the [VRCMG](https://discord.gg/7EQCmgrUnH) for manual install.
