### ISSUE TITLE
Searching Problem

### ISSUE THREAD

**Issue by ItIsWaka** [emmVRC/emmVRC-Public#1619]
Everytime I try to search an avatar [after like 10 minutes of playing the game] with the search feature, nothing happens, the avatar that I searched for doesn't appear.
Maybe the problem is that I use emmVRC and ReMod at the same time and they are not compatible in some ways? But every time it happens I just need to restart the game and it works fine.

**Comment by rakosi2** [comment]
Remod servers were under maintenance a few hours ago, try restarting VRChat and see if you continue to have issues.

**Comment by PixelTails** [comment]
it has been doing it to me to for a few months now, still waiting for it to get fixed if possible

**Comment by ItIsWaka** [comment]
The problem is not the maintenance, I had the same problem yesterday
It happens everytime, and the only way to fix it is to restart the game when it happens and for the next 10 minutes it works perfectly
