### ISSUE TITLE
Bug: can't look around

### ISSUE THREAD

**Issue by ChalupaChopper** [emmVRC/emmVRC-Public#1628]
so I updated the Melonloader and I now can't look around I wasn't sure if I should put this in bugs but it makes it unplayable for me I do like the mod and have used it for a while and I use desktop  for the moment I'm going to remove the mod

I redownloaded it and still had the problem

**Comment by thetrueyoshifan** [comment]
What other mods do you have installed? For quicker support, join and upload your log in our discord https://discord.gg/emmvrc
