### ISSUE TITLE
[FEATURE REQUEST] FAST FAVORITE (ONLY PEOPLE WHO HAVE CLONING ON)

### ISSUE THREAD

**Issue by Lucario4LyfeYT** [emmVRC/emmVRC-Public#1640]
If someone has their cloning off, their avatar will NOT be favorited.
Everyone in the lobby who has CLONING ON will have their avatars favorited. (NOT FORCE CLONING)
If someone has their CLONING OFF their avatar will NOT BE favorited.

**Comment by PixelTails** [comment]
but how would you do it without running out of favorite slots? do you choose the avatars in a menu or is it a button that adds all of them to your favorites menu instantly?

**Comment by PixelTails** [comment]
i mean, its a good idea but i still don't know what you mean

**Comment by Lucario4LyfeYT** [comment]
> but how would you do it without running out of favorite slots? do you choose the avatars in a menu or is it a button that adds all of them to your favorites menu instantly?

Both of them. Also, it's more meant towards people with VRC+, since they can have infinite emmVRC favorites.

**Comment by MintLily** [comment]
Creating a new feature request for something I already told we aren't doing, is considered abuse and will leads both of you in a ban for these request forms.

Again, will not and will never add this to the mod.
