### ISSUE TITLE
[FEATURE REQUEST] Fast block/unblock people?

### ISSUE THREAD

**Issue by Lucario4LyfeYT** [emmVRC/emmVRC-Public#1642]
Allows you to click multiple users at once and block them with one click
So if a group of people comes to annoy you, you can quickly block them

**Comment by BLANKE1** [comment]
messing with moderation via mods is pretty risky and could get you banned easily

**Comment by Lucario4LyfeYT** [comment]
> messing with moderation via mods is pretty risky and could get you banned easily

Put it under risky Features then lol

**Comment by BLANKE1** [comment]
I don't think that's something the emmVRC team wants to risk with that many amounts of people using this mod. Sure, risky functions are there, but the current functions in risky functions aren't detectable. If any of the moderation endpoints change, thousands of users could get banned for trying to use the feature.

**Comment by Lucario4LyfeYT** [comment]
> I don't think that's something the emmVRC team wants to risk with that many amounts of people using this mod. Sure, risky functions are there, but the current functions in risky functions aren't detectable. If any of the moderation endpoints change, thousands of users could get banned for trying to use the feature.

Fair enough, but I'm pretty sure mass blocking people wouldn't get you banned, but if you say it might, then I mean, I guess you're right.
