### ISSUE TITLE
[FEATURE] Account Switcher

### ISSUE THREAD

**Issue by Quaxly** [emmVRC/emmVRC-Public#1643]
One feature I'd love to see is the ability to save and switch accounts in game without needing to logout and re-enter all your login info. This feature would be very useful for people with multiple accounts as they could easily switch accounts in seconds and especially VR users as entering login info is very painful in VR. The account switcher could be on the start screen and in your menu where you click it and brings up a page showing your accounts with their basic info such as names and banners/avatars. From here you'd have the option to switch to another account or add/remove accounts. The account switcher shouldn't need to save any passwords, just tokens so it shouldn't be a security risk to add.

**Comment by PixelTails** [comment]
yes please
