### ISSUE TITLE
Just learned something about the open beta

### ISSUE THREAD

**Issue by casserolenotacassowary** [emmVRC/emmVRC-Public#1644]
so i installed the open beta because i was curious with it and as soon as i uninstall it, it completely broke MelonLoader, now VRC refuses to open and i'm convinced open beta should be AVOIDED by all EmmVRC users or general MelonLoader users

**Comment by BLANKE1** [comment]
This is not a bug report nor a feature request, it's primary common sense that mods won't work on beta builds. Just reinstall melonloader to fix this, next time put --no-mods in your launch options to prevent this.

**Comment by casserolenotacassowary** [comment]
i treid reinstalling it but that didn't seem to work, was thinking of deleting this post anyway

**Comment by casserolenotacassowary** [comment]
but seeing as there's no way to do that then guess i'll have to live with it

**Comment by casserolenotacassowary** [comment]
well this was awkward to post
