### ISSUE TITLE
VRChat mods on Oculus Quest 2

### ISSUE THREAD

**Issue by FireNotFound424** [emmVRC/emmVRC-Public#1649]
[FEATURE REQUEST] So I know you guys keep on saying that its impossible to get mods for standalone quest, but can't you just make a sideloaded app that emulates windows? That way when you launch the new app and download melon loader it works exactly like it does on PC? All you would need to do is turn on multitasking or something and add in a "Stay In the Background" option on the app. To me it seems really simple. Let me know if you can't do this.

**Comment by MintLily** [comment]
If you're asking to emulate windows on a Quest, that is merely impossible and extremely impractical to do.
Quest modding is in the plans of MelonLoader, they're just working on the current windows build at the moment, You can check and follow any possible progress on their [Discord server](https://discord.gg/2Wn3N2P).

**Comment by Myrkie** [comment]
> [FEATURE REQUEST] So I know you guys keep on saying that its impossible to get mods for standalone quest, but can't you just make a sideloaded app that emulates windows? That way when you launch the new app and download melon loader it works exactly like it does on PC? All you would need to do is turn on multitasking or something and add in a "Stay In the Background" option on the app. To me it seems really simple. Let me know if you can't do this.

if it was so simple it would of been done already
