### ISSUE TITLE
[FEATURE] Clear cache on game close

### ISSUE THREAD

**Issue by ClarityNZ** [emmVRC/emmVRC-Public#1650]
As someone with a small SSD I do have to be conscious of space, having an option to automatically clear cache when I close vrchat would be very helpful

**Comment by Janni9009** [comment]
Clearing your cache constantly will hurt your loading times and SSD lifespan unneccessarily you should only do this when something in it breaks horribly.
Consider instead to move your cache to another drive or lower it's size using the [VRChat configuration file](https://docs.vrchat.com/docs/configuration-file).
