### ISSUE TITLE
risky functions not working?

### ISSUE THREAD

**Issue by itsabirb** [emmVRC/emmVRC-Public#1651]
![Screenshot 2022-04-13 012057](https://user-images.githubusercontent.com/103564506/163132850-4bd2a7f5-d766-4215-b57b-def41604b94b.png)
![Screenshot 2022-04-13 012157](https://user-images.githubusercontent.com/103564506/163132862-f22f37d1-bddc-4a43-9936-3eba70fb6b1b.png)
my risky functions are not working at all, I have the setting set to on but they are still grayed out and wont allow me to use them, i have the most recent versions of emmvrc as well as melon loader. I've tried reinstalling melon loader as well emmvrc, I have also looked in the discord for those with similar problems but cannot find any.

**Comment by RiskiVR** [comment]
Risky Functions are disabled in worlds with the game tag, club tag, has private rooms, or the world itself doesn't allow it
