### ISSUE TITLE
Dynamic bones avatar bug

### ISSUE THREAD

**Issue by BigBoyBebop** [emmVRC/emmVRC-Public#1652]
Not exactly sure what's causing it, but on a particular avatar that I have my mods are causing the Dynamic ones on it's hair to spaz out and jitter every second and my friend who made the avatar who also uses no mods had no issues like or similar to this on both desktop and vr. If the request of cloning this avatar is needed my discord is ☆『 ↨⎞ ༻ད⎝ЯΣƊ⎠ཌ༺ ⎛↨』☆#1460

**Comment by thetrueyoshifan** [comment]
Is this issue still occuring?

**Comment by BigBoyBebop** [comment]
It's fixed now
