### ISSUE TITLE
favorites dont show nor can i look up avatars.

### ISSUE THREAD

**Issue by goredolly** [emmVRC/emmVRC-Public#1658]
ive reinstalled and uninstalled a couple times to see if that was the issue but it wasn't, i'm pretty new to all this so if anyone knows if i am missing something i would appreciate it :). ive had emmvrc for a couple months now and ive never had an issue until now so idk if its the update or not

**Comment by BLANKE1** [comment]
[Join the emmVRC discord](https://discord.gg/emmvrc) to ask for help questions, this repo is made for bug reports, and feature requests.
