### ISSUE TITLE
Emmvrc not loading with melon launcher

### ISSUE THREAD

**Issue by Deetrus0** [emmVRC/emmVRC-Public#1662]
I used to use emmvrc till I deleted vrchat and now I got back to vrchat I did the same steps downloaded melon launcher and I threw the emmvrc dll in the mods folder but when I launch up the game it isn't there

this is the log:
https://pastebin.com/f4tRuafZ

**Comment by Janni9009** [comment]
This isn't exactly the place for support, you should join the [discord](https://discord.gg/emmvrc) for that, but I can see right away that your MelonLoader version is outdated. (0.5.3, current and required for emmVRC is 0.5.4) so you will need to update it using the [installer](https://github.com/HerpDerpinstine/MelonLoader/releases/latest). If updating MelonLoader for some reason doesn't fix the issue, please head over to the discord as mentioned above.
