### ISSUE TITLE
[FEATURE] toggle for Third-person view

### ISSUE THREAD

**Issue by sanesf** [emmVRC/emmVRC-Public#1663]
I feel like having a button for it like speed, fly and things like that would be beneficial
I keep having the problem of accidentally turning third-person view on
It also mixes with some other clients I have
It would make my life a little bit easier and I would be really thankful.

**Comment by BLANKE1** [comment]
If you use mods that go out their way to call themselves "Clients" I'd recommend reading [this](https://github.com/knah/VRCMods/blob/master/Malicious-Mods.md) emmVRC will not go out it's way to support being used with other mods outside of the [VRChat Modding Group discord](https://discord.gg/7EQCmgrUnH). Either way, you can just disable hotkeys in the config file for now

**Comment by thetrueyoshifan** [comment]
A feature to turn off all of the keybinds, as well as configure each one in-game, will be (re)introduced in emmVRC v3.2.0
