### ISSUE TITLE
[QUESTION] Avatar Search Minimum Character Limit

### ISSUE THREAD

**Issue by OrniiDiien** [emmVRC/emmVRC-Public#1664]
I wanted to ask why the character limit for avatar searches now has to have a minimum of 3 characters for it to be successful? I used to be able to search with two characters minimum.
The reason why I have this question is because a character I wanted to search for avatars of has only two characters in its name ("V1").

**Comment by thetrueyoshifan** [comment]
You can also search the avatar author's name to get access to the avatar. The avatar name limitation is in place to prevent a search from accidentally getting several thousand avatars from our database.

**Comment by OrniiDiien** [comment]
That's understandable! Thanks for the answer.
