### ISSUE TITLE
Cannot access the emmvrc button

### ISSUE THREAD

**Issue by kiwiR06** [emmVRC/emmVRC-Public#1667]
With VrChats new pause UI the emmvrc menu cannot be reached due to the safe mode button being in the way, i have attached an image to evaluate. Even in VR the button does not work
![image](https://user-images.githubusercontent.com/104702039/166127313-52b6000b-f290-450c-b7a5-8459980338ae.jpg)

**Comment by Janni9009** [comment]
This is a known issue with having multiple mods using tabs and a wontfix on our side (would only cause conflicts). Grab the TabExtension mod from the [VRCMG](https://discord.gg/7EQCmgrUnH )or [MelonAssistant](https://github.com/knah/VRCMelonAssistant/releases/latest/download/VRCMelonAssistant.exe) to work around this by getting additional rows.

Also you can press Windows+Shift+S or Print Screen to take a proper screenshot that you can CTRL-V or right click & paste into most programs.
