### ISSUE TITLE
[FEATURE] frame rate limiter removal?

### ISSUE THREAD

**Issue by Theguywholikessplatoonalot** [emmVRC/emmVRC-Public#1670]
its annoying to only get 60 fps

**Comment by BLANKE1** [comment]
Ever since build 1189 (Avatar Dynamics update), the framerate is now locked to your monitor's refreshrate. If you want to unlimit your framerate currently (which is pretty useless if you have a 60hz monitor), put `--fps=0` in your launch options.

**Comment by Mezque** [comment]
<img width="81" alt="image" src="https://user-images.githubusercontent.com/31026406/167226040-f38e9d40-4849-43eb-9efc-01f46d892456.png">
vrchat restored the ability to use the --fps-NUMBER launch option to change it, I have mine set at 120.
