### ISSUE TITLE
[Feature Request] Item Respawn

### ISSUE THREAD

**Issue by Lucario4LyfeYT** [emmVRC/emmVRC-Public#1674]
It's annoying when you enter a world and all the items are just scattered around, please add a button to respawn all items in their original spot

**Comment by Hordini** [comment]
As far as I know, that would be far too risky if VRChat starts properly checking these things. How I understand it is you take ownership of all items to reset them, which is also often used in other malicious functions (giving them a reason to start checking). The only situation I'm away of that would legitimately happen is if you became Master of the Instance, so if you did so without that happening, it'd just look suspicious. Not to mention anyone who is able to see that information will know who the user that executed that function is.

**Comment by Lucario4LyfeYT** [comment]
Then put a cooldown on the respawn items button- it seems simple enough to do, plus, I do get the malicious stuff you can do with taking ownership of every item, (like item orbit and item lag) but putting a cooldown on the button so people don't spam it should fix the item lag problem I mentioned? idk tho

**Comment by thetrueyoshifan** [comment]
The issue is not having a cooldown; it's doing it at all. There would not be a safe to respawn everything without doing as Hordini said, and this would be a major red flag. Because this has a risk of being detectable and used for bans, it is not something we can consider at this time.
