### ISSUE TITLE
remove check for vrc+

### ISSUE THREAD

**Issue by NinetailsPlaysIG** [emmVRC/emmVRC-Public#1675]
i heard there is a way to remove the check for vrc+ for unlimited avatars, im not paying 100$ a year for a subscription service so i can favorite avatars when i can still get banned for using it. any help would be great thanks

**Comment by BLANKE1** [comment]
You're not following the format nor respecting VRChat's monetization, VRChat's server fees cost a lot of money this is the reason why VRC+ exists in the first place, Investor money does not last forever and also will need to be paid back. Please respect this mod's decency towards VRChat.

**Comment by NinetailsPlaysIG** [comment]
> You're not following the issue format nor respecting VRChat's monetization. VRChat's server fees cost a lot of money this is the reason why VRC+ exists in the first place, Investor money does not last forever and also will need to be paid back. Please respect this mod's decency towards VRChat.
respectfully im not paying them since 1 i dont have enough money to throw out like that, 2 they have yet to make this game optimized and is the only vr game that i have played that i have to run with 6x lower graphic settings and still get lag and 3 100$ a month is an absurd price to pay for something that without a client that risks me getting banned only gives you 75 more avatars and a few vanity things on an unoptimized game that is only popular because of all the map creators that dont get paid anything to make maps for vrchat and if they do its definitly not by vrchat

**Comment by BLANKE1** [comment]
emmVRC isn't a client, it's a MelonLoader mod. VRChat in itself runs fine, the playerbase is to blame for not running well, it's not VRChat to blame. VRC+ is $10 a month, and $100 for a year ($20 discounted off). emmVRC grants users unlimited favorites as long as they're an active VRC+ subscribed user. 25 Favorites is enough for a casual user, also take note that upload slots are entirely free.
