### ISSUE TITLE
hi i have a doubt about emmvrc plus or project plus

### ISSUE THREAD

**Issue by Emmettlove** [emmVRC/emmVRC-Public#1676]
Hi! How are you? Sorry to bother you, but I have a question regarding the emmvrc plus or project plus and the pin reset, those of us who already have saved avatars from a while ago with the pin reset are going to lose everything? because in my case I have 325 saved avatars, thank you very much for your help

**Comment by BLANKE1** [comment]
Nowhere in the announcement refers to a user wipe, so no all you'll need to do is reset your pin when the update happens (which can be done in the game included with the update). Please just ask these questions in the discord server instead of the github made for Feature Requests and Bug Reports
