### ISSUE TITLE
[FEATURE REQUEST] Instance History Confirmation

### ISSUE THREAD

**Issue by wintrrss** [emmVRC/emmVRC-Public#1687]
**Is your feature request related to a problem? Please describe.**
when trying to go through my instance history i accidently click on some old worlds i joined.

**Describe the solution you'd like**
When you click on the world you want to rejoin, ask for confirmation

**Describe alternatives you've considered**
None i havent found anything

**Additional context**

**Comment by strokenmydaek** [comment]
give us a toggle button for the risky mods

**Comment by thetrueyoshifan** [comment]
You didn’t even try to follow the template. Not one bit.
