### ISSUE TITLE
[FEATURE REQUEST]: A filter for Quest and PC avatars

### ISSUE THREAD

**Issue by YourMomsLeftFeet** [emmVRC/emmVRC-Public#1690]
### Is your feature request related to a problem? Please describe.

it's really frustrating when you search for avatars and only pc avatars pop up.

### Describe the solution you'd like

to have a filter for PC only avatars and QUEST pc ones

### Describe alternatives you've considered

 removing private avatars from the search results

**Comment by loukylor** [comment]
Duplicate of #1333
