### ISSUE TITLE
[BUG REPORT]: Portals Not Working

### ISSUE THREAD

**Issue by HuskyKurai** [emmVRC/emmVRC-Public#1691]
### Have you uploaded your log to our Discord?

No

### Describe the bug

A few days ago portals stopped working for me. I re-updated MelonLoader and changed out the EMMVRC.dll fine even though it was the same 1.5.0.0 version and no changes. Unless there's some EMMVRC function to disable portal interactions that I cannot find in any of the options, then it's a bug I am having. I checked VRChat without MelonLoader starting up and the portals worked, so I know this is an EMMVRC related issue.

### To Reproduce

.

### Expected behavior

.

**Comment by Janni9009** [comment]
There _is_ an option to disable portals in the world tweaks submenu, try toggling that and report back if it's fixed in either state, or still broken in both.

**Comment by HuskyKurai** [comment]
Found it. I wasn't expecting it to be under World as an option since I was failing with players placed portals.
