### ISSUE TITLE
old and private avatars are appearing when i look up avatars 

### ISSUE THREAD

**Issue by femboylen** [emmVRC/emmVRC-Public#1693]
### Have you uploaded your log to our Discord?

Yes

### Describe the bug

when i look up avatars old public ones and private ones only come up no new public ones come up and not all avatars come up 

### To Reproduce

[MelonLoader_22-06-15_12-09-24.340.log](https://github.com/emmVRC/emmVRC-Public/files/8904606/MelonLoader_22-06-15_12-09-24.340.log)

### Expected behavior

once this bug is fixed i expect to see new avatars appear 

### Screenshots/Logs

[Latest.log](https://github.com/emmVRC/emmVRC-Public/files/8904603/Latest.log)

**Comment by BenjaminZehowlt** [comment]
Date sorting will be removed in the next update. It is now always sorted on relevancy.

The private avatars are just due to them being public once upon a time. Please open a ticket with these.
