### ISSUE TITLE
[BUG REPORT]: <Wonky avatar search>

### ISSUE THREAD

**Issue by Timpou** [emmVRC/emmVRC-Public#1694]
### Have you uploaded your log to our Discord?

No

### Describe the bug

After the resent update the avatar search isnt working all fully, basically the order of the avatars is all messed up, like when i turn the search from most recent to oldest i get bunch of avatars that are from the middle of the time period instead of the accurate order, the other thing that i noticed happen was that it doesn't seem to search for the things that i search for, for example if i search for 'tails' i get bunch of humans which arent labeled as 'tails', they don't have the letters in the order to spell it and lastly the creators name doesnt have those either, also i tried deleting the whole vrc and mods then reinstall everything and it did nothing
This isnt anything too huge but it would be nice to get fixed, after all it does effect the experience on vrc.

### To Reproduce

1. open vrchat and open avatar menu
2. search for something (like what you usually search for)
3. see the avatars being either in random order from what they used to be or/ and some random avatars that dont have anything to do with what you searched for

### Expected behavior

i just hope that the avatar search would turn into the order it used to/ should be, after all its hard to tell if there's any new avatars that have popped up lately.

### Screenshots/Logs

i did not take a screen shot, didnt realize to
but this error is easy to test specially if theres people who use the mod and search for certain avatars frequantly.

### Additional context

sometimes the images dont also show up, or avatar search may show some private avatars that one cannot use, it feels little frustrating to see those there when one cannot turn into them.

**Comment by BenjaminZehowlt** [comment]
Date sorting will be removed in the next update. It is now always sorted on relevancy. Some of the avatars shown could be the author’s old name
