### ISSUE TITLE
[FEATURE REQUEST]: Clone Someone's Avatar From Their Profile

### ISSUE THREAD

**Issue by TheLordOfdKings** [emmVRC/emmVRC-Public#1695]
### Is your feature request related to a problem? Please describe.

Whenever I see someone with an avatar on that looks interesting, and I want it, but they aren't in the world or offline, I might want to clone the avatar from their profile.

### Describe the solution you'd like

I sometimes see a friend or someone else with an avatar on that I would like to check out or have, and I kind of want something like a force cloner, but from the user's profile. If this is possible, thank you.

### Describe alternatives you've considered

I guess an alternative could be going to the world of whoever has that avatar, but what if they are offline?

**Comment by rakosi2** [comment]
We will not be adding this as a feature. Please refer to our Feature Blacklist here: #7

**Comment by Janni9009** [comment]
Also, regarding the "considered alternatives" section, it's not actually possible to get an avatar id from a user who is not in your instance.
