### ISSUE TITLE
[FEATURE REQUEST]: Custom UI Sounds

### ISSUE THREAD

**Issue by realKaitoHayashi** [emmVRC/emmVRC-Public#1696]
### Is your feature request related to a problem? Please describe.

It's not related to a problem, but if we have custom menu music, what if we had custom UI sounds of our own?

### Describe the solution you'd like

There should be folders of each UI sound (ex. Selection, Worlds/Avatars/Socials menu open/close, etc.) by each sound via its own folder of each UI sound. However due to VRChat being developed on Unity, they all should be OGG.

### Describe alternatives you've considered

If not, there should just be one folder but the files have to be a specific name of the custom UI sound. It won't work if its not the specific name of the ogg file. It cannot be randomized and there should be only 1 per custom sound.

**Comment by Janni9009** [comment]
This seems more like something [Styletor](https://github.com/knah/VRCMods/issues) should implement.
(also just a small note: it's specifically mp3s that have issues at runtime, even raw wave audio works perfectly fine)
