### ISSUE TITLE
[BUG REPORT]: When favoriting an avatar you created using EMM, EMM does not load the avatar currectly in the favorites list.

### ISSUE THREAD

**Issue by ilovedogesyay** [emmVRC/emmVRC-Public#1697]
### Have you uploaded your log to our Discord?

No

### Describe the bug

The main reason I got EMM was to bypass the 100 created avatars limit, as the built in created avatars list will stop expanding at 100 and delete old avatars from the list. Whenever I try to favorite an avatar I have created using the emmVRC favorite, the avatar shows up in emmVRC favorites at first and it works as it should, letting me switch intot he avatar from the emmvrc favorites and everything, but when I restart VRchat, the emmvrc favorites list does not properly display the image icon for the avatar and it does not let me delete the avatar OR remove the avatar from my favorites. It simply says "Avatar not found".

### To Reproduce

1. Favorite an avatar from your "My Creations" list
2. Restart VRC
3. Try to switch into or delete the avatar that you favorited in step 1.

### Expected behavior

I expected the favorited avatar to function normally as any avatar would using the emmVRC favorites list, allowing me to switch into or delete the avatar whenever.

**Comment by BenjaminZehowlt** [comment]
Please provide logs, and sounds like you’re running a version older than 3.3.0

**Comment by BenjaminZehowlt** [comment]
No response for over a week, closing.
