### ISSUE TITLE
[FEATURE REQUEST] Always Join Full Instance

### ISSUE THREAD

**Issue by kasigawa** [emmVRC/emmVRC-Public#1698]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I can't join a full instance. 

### Describe the solution you'd like

Simply bypass the full instance limit. 

### Describe alternatives you've considered

none

**Comment by BenjaminZehowlt** [comment]
Yes, let’s bypass something that’s entirely enforced serversided. This won’t and can’t be implemented.
