### ISSUE TITLE
[BUG REPORT]: "Not connected to the emmVRC network" Please help.

### ISSUE THREAD

**Issue by Someone2344** [emmVRC/emmVRC-Public#1699]
### Have you uploaded your log to our Discord?

No

### Describe the bug

I downloaded everything and followed every step.
but I got hold in my tracks once I saw this.

"Not connected to the emmVRC network"

I would like a fully detail explanation on how to fix this please..

### To Reproduce

1. Open the game
2. wait for the game to load.
3. Press "Crtl + E"
4. Boom "Not connected to the emmVRC network"

### Expected behavior

Would just search avatars and do everything I wanted

**Comment by BLANKE1** [comment]
Please attempt at reading notifications that are easily shown at you in the emmVRC tab in the quick menu, and read them you'll be able to make a pin within that notification, and use the Discord server instead for simple issues. This isn't a bug report, this is just complete user error.
