### ISSUE TITLE
[BUG REPORT]: Menu expando button in emmvrc settings exists, and doesn't do anything

### ISSUE THREAD

**Issue by forever-and-a-day** [emmVRC/emmVRC-Public#1700]
### Have you uploaded your log to our Discord?

No

### Describe the bug

The emmvrc settings menu has a menu expando button (the little square inside the big square with an arrow) in the corner that doesn't do anything. Since emmvrc doesn't have any settings in the big menu, this button should be removed. 

### To Reproduce

1. Go to emm tab
2. click settings
3. look at expando button in upper right hand corner
4. click on it
5. observe absolutely nothing 

### Expected behavior

No button, as emmvrc does not add any settings pages to the main/big menu. 

### Screenshots/Logs

![expando](https://user-images.githubusercontent.com/10383240/178133602-5aa8360f-4ed9-46f2-b559-23f45d14a768.PNG)

**Comment by BenjaminZehowlt** [comment]
Please read the tooltip
![image](https://user-images.githubusercontent.com/16182181/178133799-cc37db91-18af-4eef-b214-7b3217186dba.png)

It is known ingame export is broken right now.
