### ISSUE TITLE
[BUG REPORT]: ttyf.me link to EULA is dead

### ISSUE THREAD

**Issue by mickplouffe** [emmVRC/emmVRC-Public#1701]
### Have you uploaded your log to our Discord?

No

### Describe the bug

Just installed emmVRC and join the discord. Both have http://ttyf.me/emmvrceula to accept, however, the link is broken.

### To Reproduce

1. Go to: http://ttyf.me/emmvrceula

### Expected behavior

The short link should go to the EULA to then be able to read it.

**Comment by rakosi2** [comment]
Fixed
