### ISSUE TITLE
[Bug]: EmmVRC Tab Unclickable

### ISSUE THREAD

**Issue by SpeedRunnerFuchs-Wulf** [emmVRC/emmVRC-Public#1703]
### Is your feature request related to a problem? Please describe.

Due to the amount of mods I have, I have a hard time accessing emm's menu due to how crowded it is at the bottom of the quick menu (that section where you can select the camera tab).

### Describe the solution you'd like

Could I please reaquest an option to toggle on a button in one of the wing menus so I have another way to access emm's menu?

### Describe alternatives you've considered

A different solution might be to add the ability to scroll that tab section at the bottom of the quick menu.

### Additional context

I hope this request isn't too much to ask of you, dear developers.

**Comment by BenjaminZehowlt** [comment]
Please download TabExtension https://api.vrcmg.com/v1/mods/download/280
