### ISSUE TITLE
[FEATURE REQUEST]: Mass avatar unfavoriting.

### ISSUE THREAD

**Issue by SpenniS** [emmVRC/emmVRC-Public#1706]
### Is your feature request related to a problem? Please describe.

Going through multiple pages to unfavorite an avatar just to be sent all the way back to page 1 is a bit frustrating to me.

### Describe the solution you'd like

A way to select multiple avatars from the emmvrc favorites list and unfavorite them all at once.

### Describe alternatives you've considered

I've thought about maybe starting over with a whole new list but recollecting them would be a pain because, I'll be honest, I'm lazy lol and as I stated above, removing one sends me all the way back to the 1st page.

**Comment by BenjaminZehowlt** [comment]
Coincides with #1705
