### ISSUE TITLE
[Bug] Soft Lock

### ISSUE THREAD

**Issue by Pigiboy200** [emmVRC/emmVRC-Public#36]
I accidentally put the menu button under the button to the discord so I cant press the menu any more

**Comment by Hordini** [comment]
Please ask for help in the emmVRC Discord's #help-and-support channel.

discord.gg/emmvrc

**Comment by thetrueyoshifan** [comment]
Bug fixed with 2.0.2. Please ask in #help-and-support to fix the positioning.
