### ISSUE TITLE
[BUG] 3.0 Parameter Saving Doesn't Work

### ISSUE THREAD

**Issue by DFliyerz** [emmVRC/emmVRC-Public#37]
I tried the new parameter saving feature and it definitely generates a file containing the saved parameters, but it doesn't seem to apply once you switch back into the avatar.

**Comment by Hordini** [comment]
Hello, did you click the 'Save Avatar Parameters' button in emmVRC Functions > Player Tweaks with modified parameters while in a 3.0 avatar?

**Comment by fwenny** [comment]
Can confirm. Changed params, clicked save, swapped avatar, default values still active.

**Comment by thetrueyoshifan** [comment]
What mods do you have installed? We're investigating a potential incompatibility with MultiplayerDynamicBones

**Comment by thetrueyoshifan** [comment]
Fixed with 2.0.6
