### ISSUE TITLE
[Feature] Save Avatar Parameters relocation

### ISSUE THREAD

**Issue by yehitmebo** [emmVRC/emmVRC-Public#38]
If possible, could the Save Avatar Parameters button be relocated or duplicated to the Quick Menu?

Possibly replacing the Emote button or Report World button? 

Thanks! <3

**Comment by XhailOrigin** [comment]
Hello Please modify your title to include the proper format
[Bug] or [Feature]

**Comment by yehitmebo** [comment]
> Hello Please modify your title to include the proper format
> [Bug] or [Feature]

**Comment by yehitmebo** [comment]
> Hello Please modify your title to include the proper format
> [Bug] or [Feature]
