### ISSUE TITLE
[Bug] Avatar 3.0 parameter saving breaks avatar for other players

### ISSUE THREAD

**Issue by tnt925** [emmVRC/emmVRC-Public#43]
saving perms causes my avatar to stay default for other players. changing perms does not show for them

**Comment by thetrueyoshifan** [comment]
What mods do you have installed? We're investigating a potential incompatibility with MultiplayerDynamicBones

**Comment by tnt925** [comment]
The only other mod I have installed is player volume control. The issue did
seem to resolve itself after quitting and going back into the game

**Comment by thetrueyoshifan** [comment]
Alright. Please open another issue if it comes back, and we'll look into it further
