### ISSUE TITLE
[Feature] A little icon that shows if they are also using emm

### ISSUE THREAD

**Issue by ImDarkener** [emmVRC/emmVRC-Public#44]
So the emm icon would appear on someone's nameplate if they also happen to be using emm as it would just be nice to be able to see who is also using the mod.

**Comment by RiskiVR** [comment]
We won't be adding that for the safety of emmVRC users, because it can be used maliciously to target others.

**Comment by thetrueyoshifan** [comment]
This is planned as an opt-in feature of the emmVRC Network

**Comment by dariendark** [comment]
hate to be that guy, but any marker the mod creator would have to put on for emm users to recognize each other could easily be used by vrchat to locate and ban emm users, even though emm follows a bunch of self-induced rules, doesn't change the fact that mods of any kind are against the terms of use. any kind of detectible branding would give the vrchat devs a literal target on our backs.
