### ISSUE TITLE
[Bug] The menu colors are different even when menu color is off

### ISSUE THREAD

**Issue by Fire9ball** [emmVRC/emmVRC-Public#45]
The colors are different than original game even without emmvrc color on, its alot brighter.

Without EmmVRC
![16-30-50 121](https://user-images.githubusercontent.com/17534338/96322573-7ffe8b80-0fce-11eb-9c00-719d1ca1206b.png)

With EmmVRC
![VRChat_1920x1080_2020-10-16_16-39-26 333](https://user-images.githubusercontent.com/17534338/96322593-8e4ca780-0fce-11eb-8923-a2f42222550a.png)

btw I have my custom color set to red, so its not that

**Comment by Provini** [comment]
Just to check, did you do something to hide emmVRC in the second image? As I don't see anything referencing emmVRC in the quick menu.

**Comment by Fire9ball** [comment]
> Just to check, did you do something to hide emmVRC in the second image? As I don't see anything referencing emmVRC in the quick menu.

sorry i forgot to mention i have a client that hides emmvrc button, here is just emmvrc with default settings

![adsaapture](https://user-images.githubusercontent.com/17534338/96323131-bb9a5500-0fd0-11eb-8773-3cc9daad137b.PNG)

**Comment by XhailOrigin** [comment]
Hello! thanks for the post! Please remember to follow the formatting outlined in this post https://github.com/emmVRC/emmVRC-Public/issues/5

**Comment by Fire9ball** [comment]
> Hello! thanks for the post! Please remember to follow the formatting outlined in this post #5

Ok i will fix it

**Comment by thetrueyoshifan** [comment]
This is intentional behaviour, and is required for the color module to work the way it is intended.
