### ISSUE TITLE
[Feature] Set a animation parameter on a avatar for if emm is present or has loaded avatar

### ISSUE THREAD

**Issue by UiharuKazari2008** [emmVRC/emmVRC-Public#47]
Can you drive a avatar animation parameter (Not VRChat Avatar Parameter) for such things like:

emmEnabled - The user has avatar and has emm running
emmAvaLoaded - Avatar has loaded and parameters are set. I ask for this because I have my avatar setup to drive paramers but I want it to not drive them on initial load of the saved state
emmAvaOwner - The user owns the avatar, can be used to lock that avatar to only the owner, if you combine this with IsLocal you can lock it locally by globally it would work

**Comment by thetrueyoshifan** [comment]
This could lead to potential malicious uses, such as pointing out emmVRC users on public avatars
