### ISSUE TITLE
[Feature] Add a Show Avatar Author button on the Avatar Page

### ISSUE THREAD

**Issue by Provini** [emmVRC/emmVRC-Public#49]
Oftentimes when using a mod like AvatarStatsShowAuthor, I still can't use it to show the author because I have to wait for the avatar preview to completely load before I'm able to view that stats and click the avatar author button, and sometimes the preview breaks completely, preventing being able to use that mod. So a button on the avatar page would be better so you don't have to wait for the preview and will still work if the preview fails or infinite loads, not to mention skipping a button press completely.

**Comment by mr2meowsYT** [comment]
just go to quick menu > emmvrc functions > player tweaks > select current user > show avatar author

**Comment by Provini** [comment]
For that you have to change into the avatar first, instead of just clicking on it. It's also nice to only have one step instead of four for convenience.

**Comment by thetrueyoshifan** [comment]
Avatar author can now be accessed via Avatar Details > Avatar Author
