### ISSUE TITLE
[Feature]add support for turning on or displaying veteran and legendary ranks

### ISSUE THREAD

**Issue by sophia1000** [emmVRC/emmVRC-Public#50]
its just like the titles says add support for turning on or displaying veteran and legendary ranks. it would be neat to be able to see that like it could be off by default but with settings to turn it on and give it a color. just a fun little addon that would be nice

**Comment by Provini** [comment]
The mod "OGTrustRanks" from VRChat Modding Group can provide this.

**Comment by yui-123** [comment]
nice though would be nice to all be in one mod

**Comment by thetrueyoshifan** [comment]
Impossible with the recent removal of Veteran and Legendary ranks from the API
