### ISSUE TITLE
[FEATURE]see other mods in function button change

### ISSUE THREAD

**Issue by Lewko6702** [emmVRC/emmVRC-Public#53]
You cant see other mods while changing the functions button position which causes overlapping so i think the menu should try to show other mods in the menu to prevent the issue of overlapping

**Comment by thetrueyoshifan** [comment]
This is too broad of a question, as there are multiple mods and different ways of creating buttons. What mods specifically do you want compatibility with?

**Comment by Lewko6702** [comment]
> This is too broad of a question, as there are multiple mods and different ways of creating buttons. What mods specifically do you want compatibility with?

Totallywholesome is a good start as i have personally made the mistake of overlapping it at one point

**Comment by loukylor** [comment]
Something like this isn't particularly possible, as heuristic detection of other mods' buttons is pain, and going through other mods' code is even more pain.

**Comment by thetrueyoshifan** [comment]
No longer neccessary due to VRChat UI changes
