### ISSUE TITLE
[FEATURE] Fullbody calibration save when quit game and reopen or crash 

### ISSUE THREAD

**Issue by Kay3012** [emmVRC/emmVRC-Public#54]
I love the new fbt save although what bugged me is when I crashed and I had to recalibrate all my avatars which is switch into all the time every second and I though that whenever u do crash and reopen the game it should say would u like to keep ur old calibration save or start from new, saves u the effort into standing up to calibrate after crashing.

**Comment by Provini** [comment]
Closing as it's a duplicate of https://github.com/emmVRC/emmVRC-Public/issues/30
