### ISSUE TITLE
[FEATURE] show the ping for everyone in the world next to there name on the side panel 

### ISSUE THREAD

**Issue by sophia1000** [emmVRC/emmVRC-Public#56]
i think this would be really nice to have as it would make it easy to tell if someone is lagging for desyncing and shouldn't be to hard as its already displayed in the network debug panel. like if its possible to do like would be neat to be able to see that.

**Comment by yui-123** [comment]
and the debug panel is annoying to use in vr

**Comment by thetrueyoshifan** [comment]
Will be added in emmVRC 2.4.1
