### ISSUE TITLE
[BUG] EmVRC will not launch when I launch VRChat.

### ISSUE THREAD

**Issue by Virodox** [emmVRC/emmVRC-Public#58]
![Screenshot_3](https://user-images.githubusercontent.com/73130534/96493979-b416be00-1213-11eb-9cd6-52210fb0fe68.png)
Haven't been able to use the mod since the last update. I've tried reinstalling melon loader, EmVRC, VRC nothing works.

**Comment by Provini** [comment]
Update UIExpansionKit. It's probably out of date if you have it.

**Comment by Virodox** [comment]
This fixed the issue actually. WOW thanks man!
