### ISSUE TITLE
[FEATURE] vrc family tree

### ISSUE THREAD

**Issue by yui-123** [emmVRC/emmVRC-Public#59]
ok so this a a more out their request but this is been something i have always wanted to see as a thing and as emm is easily the most common client to this is the only way i could ever see it being a thing. but basically like how you can add a note to a player there should be a family one with like mom dad brother sister kinda thing that you can put on people and sync it to the emm network and with that data you could easily make a expansive model of all the family relations in vrchat or even make the tags sync across accounts like if someone has 2 kids those two would show up as brothers or sisters to each other. this would just be something really fun to meet new people in your family as alot of people participate in vrc family's it would be really fun. and if you got all that data and made a program at some point that could put it all together you would be the first to ever really make a full vrchat family tree. this has always been a meme to do like make the vrc spiderweb kinda thing. i really hope you find this as funny an idea as i do and make it a thing.

**Comment by yui-123** [comment]
like imagine making a website at some point as well for it were you could just put your name and it will show you your family spiderweb and you can follow it to find other people in you web. i really hope this becomes a thing as this would just be funny to see and the only way i can see that is emm doing it as i really doubt vrchat will and probably half of vrchat uses emm

**Comment by thetrueyoshifan** [comment]
This sounds like a fun idea. However, it is really entirely out of the scope of emmVRC, and would be better suited as an individual mod.
