### ISSUE TITLE
[FEATURE] add some form of anti crash

### ISSUE THREAD

**Issue by yui-123** [emmVRC/emmVRC-Public#63]
what i think would be a good fit for emm would be a form of anti crash or advanced safety. i know there are other mods that do it but emms ui is alot better along with having it all in one mod would be nice. crashers are way to prevalent it doesn't have to be perfect like if most crashes get blocked would be really nice. along with this would benefit everyone using this mod

**Comment by GroaxyVRC** [comment]
AdvancedSafety and ParticleandBoneLimiter by knah are really good mods, adding some sort of anticrash is a hit or miss as not everything can be detected, and it'll just clutter the code for emms imo, sticking to seperate mods for anticrash is the best way to go

**Comment by yui-123** [comment]
ok i just liked the idea of it all being in one mod as emm does ui alot better to but understandable

**Comment by thetrueyoshifan** [comment]
This is out of the scope of emmVRC, as it's too broad of a topic to just implement, due to many different forms of crashing.
