### ISSUE TITLE
[FEATURE] auto esp for blocked users

### ISSUE THREAD

**Issue by yui-123** [emmVRC/emmVRC-Public#64]
it would be nice if someone blocks you or you blocked them for esp to turn on automatically for just them. or like you join a world and someone has you blocked it makes it alot more obvious

**Comment by yui-123** [comment]
in most cases people block you for small reasons and in most cases asking to get unblocked works. but this is especially useful in game worlds as someone having you blocked and you not knowing can make things confusing. in the least a system to show someone blocked you as if they block you vrchat doesn't tell you or display it in anyway.

**Comment by thetrueyoshifan** [comment]
This could be used for malicious uses, such as targeting users that blocked you, so this will not be implemented.
