### ISSUE TITLE
[Bug] VRChat's HUD and Nameplate keybinds doesn't correctly change the toggle status in Quick Menu > UI Elements.

### ISSUE THREAD

**Issue by Provini** [emmVRC/emmVRC-Public#65]
This only happens when emmVRC is loaded.

**Comment by thetrueyoshifan** [comment]
This is known as of implementation. We're going to try and have this fixed by the next update.

**Comment by Provini** [comment]
Closing due to changes made from a recent VRChat update.

**Comment by thetrueyoshifan** [comment]
This is a feature that I still want to fix, along with all of the HUD and nameplate toggle systems

**Comment by thetrueyoshifan** [comment]
Will be fixed with emmVRC 2.4.1
