### ISSUE TITLE
[FEATURE] Mod Compatibility - OldMate

### ISSUE THREAD

**Issue by Hordini** [emmVRC/emmVRC-Public#67]
Compatibility with the OldMate mod by dave-kun that allows you to set nicknames for users. The only incompatibility with them is the name displayed in the emmVRC HUD not changing to the nickname.

Repo (published in the VRCMG): https://github.com/dave-kun/OldMate

**Comment by BenjaminZehowlt** [comment]
OldMate is no longer maintained or even works properly in VRCMG closing for now.
