### ISSUE TITLE
[FEATURE] Remove unused icons

### ISSUE THREAD

**Issue by mist1321** [emmVRC/emmVRC-Public#70]
Removal of some unused icons for desktop menu in vrchat for

1. sitting/standing
2. UI elements
3. go home
4. respawn

all those can be used in the quick keybindings anyway.

**Comment by yui-123** [comment]
ya like the ability to remove any of the default buttons and replace them with the emm buttons would be nice.

**Comment by yui-123** [comment]
i have playspace so literally never touch sitting play
