### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by smartyman16** [emmVRC/emmVRC-Public#71]
everytime i dissable noclip i crash

**Comment by Hordini** [comment]
Please post your latest MelonLoader log file in the emmVRC Discord's #help-and-support channel

**Comment by smartyman16** [comment]
> Please post your latest MelonLoader log file in the emmVRC Discord's #help-and-support channel

where can i find it ?

**Comment by XhailOrigin** [comment]
To find your Log file, navigate to VRChat's root directory. The path should be something like this:
Steam: C:\Program Files (x86)\Steam\steamapps\common\VRChat
Oculus: C:\Oculus Apps\Software\vrchat-vrchat

Alternatively, you could find it through the launcher you're using:
Steam: Steam Library > right-click VRChat > Manage > Browse local files
Oculus: Oculus Library > ••• > Details > Copy location to Clipboard. Open File Explorer and paste it into the directory bar (or manually navigate to it).

From there, open the Logs folder, then drag and drop the latest MelonLoader log file into Discord.
