### ISSUE TITLE
(Feature) Stealth Mode Additional Support

### ISSUE THREAD

**Issue by CrimsonMoonFQ** [emmVRC/emmVRC-Public#73]
This is more so to see about getting added support to hide "Mod Settings" in the setting menu and the "MControl" mod in the main menu with the Emmvrc functions in the "Report Worlds" menu when in Stealth mode.
![menu](https://user-images.githubusercontent.com/73706742/97720963-e1c2f900-1a96-11eb-93cc-da98833a9584.PNG)
The "Mcontrol" has no enable or disable toggle under "Mod Settings".
![music1](https://user-images.githubusercontent.com/73706742/97721382-5e55d780-1a97-11eb-9376-b6a7154cc8b0.PNG)

**Comment by thetrueyoshifan** [comment]
These are outside of the scope of emmVRC, and would be better suited as additions within those mods themselves.
