### ISSUE TITLE
unable to see quest compatibility properly

### ISSUE THREAD

**Issue by GalacticAJanya** [emmVRC/emmVRC-Public#74]
Hello,
Theres bug in avatar search and favorites with compatibility signs, every avatar shows up as quest comaptible even though its not making finding that kind of avatars a nightmare.

**Comment by XhailOrigin** [comment]
I am closing this thread because we are aware of this issue and will have a fix in the future. Before posting please ensure you have read the pinned Known Bugs post. Thanks :D
https://github.com/emmVRC/emmVRC-Public/issues/6
