### ISSUE TITLE
[FEATURE] See what avatars a person has

### ISSUE THREAD

**Issue by PotatoPotahto** [emmVRC/emmVRC-Public#75]
The name is pretty self-explanatory, When you are on someone's profile, (Either through searching it through social or clicking them in-game) Under emmVRC functions, there will be an option to view inventory, or view avatars. What this will do, is show you what avatars this person HAS in their favorites, (Not the feature that's currently in, that only shows the avatars they MADE.) and this would be useful so if you were looking for a certain avatar you saw online, you can look at the username of the person and find the avatar. Thanks!

**Comment by yui-123** [comment]
as far as i know the vrchat favorites list of other users isent accessible on vrchats api anywhere now if they wanted you to be able to share your emm favorites list that would be possible. though that would have to be a opt in thing like chose to let others see it or just friends. now that would be cool to have and might be something they would do.

**Comment by thetrueyoshifan** [comment]
This will not be added, for privacy reasons.
