### ISSUE TITLE
[BUG REPORT] Instant Restart not functioning VIDEO PROVIDED

### ISSUE THREAD

**Issue by BLANKE1** [emmVRC/emmVRC-Public#76]
What the title says ^. Seems to be happening to select people such as me

https://streamable.com/ay0mjj

**Comment by thetrueyoshifan** [comment]
I am not able to reproduce this. Can you attach a screenshot of your VRChat folder?

**Comment by BLANKE1** [comment]
![image](https://user-images.githubusercontent.com/68296465/97764081-77807780-1adb-11eb-94c5-237f9d5f8c39.png)

Currently just a normal install folder

**Comment by GroaxyVRC** [comment]
I've had this issue a couple days ago aswell ^ Not sure what caused it but happened 3 times in a row

**Comment by thetrueyoshifan** [comment]
Is this still going on? I have not been able to reproduce this issue thus far, and I'm not sure this is an emmVRC issue specifically.

**Comment by GroaxyVRC** [comment]
It seems to be like a chance to happen I'm not sure what causes it
