### ISSUE TITLE
[BUG] Master Icon doesn't disappear with nameplates

### ISSUE THREAD

**Issue by GroaxyVRC** [emmVRC/emmVRC-Public#78]
https://i.imgur.com/zvPLkYr.png

**Comment by thetrueyoshifan** [comment]
Does this only occur when using the CTRL+N shortcut?

**Comment by GroaxyVRC** [comment]
Yes UI Elements nameplate does hide the crown but the shortcut does not

**Comment by thetrueyoshifan** [comment]
Will be fixed with emmVRC 2.4.1
