### ISSUE TITLE
Mmm..global dynamic bones don't work on...PP

### ISSUE THREAD

**Issue by manhk2016** [emmVRC/emmVRC-Public#79]
anyone got the same problem..

**Comment by Dragonstrife7** [comment]
unsure if this is the same problem your having or maybe another issue. Following error appears:
[MelonLoader_20-10-31_06-26-48.044.log](https://github.com/emmVRC/emmVRC-Public/files/5468954/MelonLoader_20-10-31_06-26-48.044.log)

**Comment by manhk2016** [comment]
> unsure if this is the same problem your having or maybe another issue. Following error appears:
> [MelonLoader_20-10-31_06-26-48.044.log](https://github.com/emmVRC/emmVRC-Public/files/5468954/MelonLoader_20-10-31_06-26-48.044.log)

YEs

**Comment by thetrueyoshifan** [comment]
This should potentially have been fixed for a long time. If the issue still persists, please open a new issue with fresh logs
