### ISSUE TITLE
Disabling Report User button 

### ISSUE THREAD

**Issue by Xiaolinshowdown** [emmVRC/emmVRC-Public#87]
When I try to enable it, people can still report me. I have tested it in the past and I couldn't be reported but now I can be.

**Comment by BLANKE1** [comment]
disabling report button doesn't mean globally and would be abused maliciously if it was global. It's local so it gives you more room in the user select quick menu screen.

**Comment by Hordini** [comment]
CLOSED
The intended use of the "Disable Report User" toggle on the 6th page of the emmVRC Settings is to locally disable the button in the user interact menu, not make you unreportable by other players.
