### ISSUE TITLE
[BUG] emmVRC can't update the HUD

### ISSUE THREAD

**Issue by tetra-fox** [emmVRC/emmVRC-Public#88]
Upon opening the game in VR, when emmVRC tries to update the HUD once a connection is established to the emmVRC network, it can't find the menu game object and leaves the HUD looking like this:
![hud](https://cdn.discordapp.com/attachments/749628706548613191/773343532864765982/20201103193022_1.jpg)

This is my full [MelonLoader log](https://github.com/emmVRC/emmVRC-Public/files/5485507/MelonLoader_20-11-03_19-27-02.961.log), but the only point of interest is this error that gets thrown when a connection is established:

```
[19:27:19.599] [Error] System.NullReferenceException: Object reference not set to an instance of an object
  at emmVRC.Menus.VRHUD+<Loop>d__10.MoveNext () [0x000e7] in <fc23fb90d8774768a160b12bf98bd2da>:0 
  at MelonLoader.Support.MelonCoroutines.ProcessNextOfCoroutine (System.Collections.IEnumerator enumerator) [0x0000d] in <6c8cecdda6ba441b84783629ba0f0ae0>:0
```

It seems like I'm the only one with this problem as I've asked several friends about it and can't seem to find any information online, but any help or fix is appreciated.

**Comment by Provini** [comment]
Try deleting the MelonLoader folder and version.dll and reinstall i t.

**Comment by tetra-fox** [comment]
Same result; I also attempted to reinstall the game entirely earlier which didn't work either.

**Comment by BLANKE1** [comment]
What is your build of VRChat?

**Comment by tetra-fox** [comment]
Latest, 1008

**Comment by Provini** [comment]
Alright. Is this through SteamVR or Oculus?

**Comment by tetra-fox** [comment]
SteamVR

**Comment by thetrueyoshifan** [comment]
Please update your VRChat to build 1010 and try again. I am unable to reproduce this on the latest VRChat version

**Comment by tetra-fox** [comment]
Still occurs on 1010

**Comment by Provini** [comment]
When you reinstalled VRChat, did you delete the VRChat folder completely too?

**Comment by tetra-fox** [comment]
Yeah, I also removed the VRChat folder from my AppData

**Comment by Provini** [comment]
Can you try completely reinstalling both dependencies?

[.NET Framework 4.7.2 Runtime] https://dotnet.microsoft.com/download/dotnet-framework/net472
[Microsoft Visual C++ 2015-2019 Redistributable] https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by tetra-fox** [comment]
Reinstalling the .NET Framework fixed this, thank you for all of your help!
