### ISSUE TITLE
[Bug] Two-Axis Puppet Not applying for some avatars

### ISSUE THREAD

**Issue by rakosi2** [emmVRC/emmVRC-Public#90]
Some 3.0 Avatar are not having their Parameters reapplied from a Two-Axis Puppet however Parameters from Radial Puppet does get reapplied from the same Avatar. 

Avatars observed where Two-Axis Puppet Parameters does not reapply:
Hugh by 乂 V Ｚ
LolyaVanillaRedSDK3 by XJLE6OGÄNGER

Avatars observed where Two-Axis Puppet Parameters does reapply:
Kisaragi_purple_rimlight_sdk3 by vololya

**Comment by BenjaminZehowlt** [comment]
Parameter saving is now part of the base game.
