### ISSUE TITLE
[BUG] BetterLoadingScreen causes emmVRC's Color Changer to throw an error.

### ISSUE THREAD

**Issue by ChinatsuHS** [emmVRC/emmVRC-Public#91]
[18:28:02.012] [MelonLoader] [emmVRCLoader] [Error] System.NullReferenceException: Object reference not set to an instance of an object
  at emmVRC.Hacks.ColorChanger.ApplyIfApplicable () [0x00bfe] in <bd7c12f0676047fc9d8a0b9df1937312>:0

not gambreaking but will share so you guys can fix it

**Comment by Provini** [comment]
Do you use BetterLoadingScreen?

**Comment by ChinatsuHS** [comment]
> Do you use BetterLoadingScreen? I can confirm this occurs when BetterLoadingScreen is active, as it's try to apply colors to the normal backround, which is now can't since the Loading Screen is replaced. A slight compatibility check may be needed.

Yes i have BetterLoadingScreen.

**Comment by Provini** [comment]
Okay. I've revised the title to reflect that.

**Comment by Provini** [comment]
Closed as this is fixed as of emmVRC 2.2.0.
