### ISSUE TITLE
[BUG] New/Returning users of emmVRC who have not set a PIN may not require it to connect to the Network.

### ISSUE THREAD

**Issue by Provini** [emmVRC/emmVRC-Public#92]
The Set Pin notification can be ignored and connect to the network fine when it shouldn't. This is the same even if you restart your game until you Set Pin. Users who have the "Login" button but never created a PIN as far as I know works as normal. People who already have a PIN set works as normal.

What I'm thinking that considering the PIN is blank, emmVRC may see it as a correct PIN and connect you anyways, despite not being set and is blank.

**Comment by thetrueyoshifan** [comment]
This is intended behavior, to allow existing emmVRC users to still connect, despite not having a pin, so they can set one themselves.

**Comment by bromo1971** [comment]
how do i create a account to the emmvrc network?

**Comment by rakosi2** [comment]
@bromo1971 we can reset your pin if you join our Discord over at https://discord.gg/emmvrc and just create a network support ticket.
