### ISSUE TITLE
emmVRC just won't load 

### ISSUE THREAD

**Issue by CaptainFallout616** [emmVRC/emmVRC-Public#94]
I have downloaded a new version and restarted vrchat but not even the add on for the menu will appear melonloader is working but no mod is.

**Comment by Provini** [comment]
Can you provide your log in the #help-and-support channel please?

**Comment by CaptainFallout616** [comment]
I don't really code or do anything like that so I don't know what you mean by "VRChat/Logs" if you can please elaborate that would be great.

**Comment by rakosi2** [comment]
To find your Log file, navigate to VRChat's root directory. The path should be something like this:
Steam: C:\Program Files (x86)\Steam\steamapps\common\VRChat
Oculus: C:\Oculus Apps\Software\vrchat-vrchat

Alternatively, you could find it through the launcher you're using:
Steam: Steam Library > right-click VRChat > Manage > Browse local files
Oculus: Oculus Library > ••• > Details > Copy location to Clipboard. Open File Explorer and paste it into the directory bar (or manually navigate to it).

From there, open the Logs folder, then drag and drop the latest MelonLoader log file into Discord. https://discord.gg/SpZSH5Z
