### ISSUE TITLE
[BUG] Avatar searching issues

### ISSUE THREAD

**Issue by Wunder-Wulfe** [emmVRC/emmVRC-Public#96]
Once i reached around 255 or 256 avatar favorites, searching loses functionality and it doesnt actually load any search items or show how many items were found.
Reducing my favorites seemed to fix the issue. Sometimes this happens regardless though and fixes itself later on usually by unfavoriting avatars or searching enough times.

**Comment by rakosi2** [comment]
Similar to ticket #81

**Comment by thetrueyoshifan** [comment]
Should be fixed in the new version of emmVRC
