### ISSUE TITLE
[Bug] Crash when exiting flight mode

### ISSUE THREAD

**Issue by UiharuKazari2008** [emmVRC/emmVRC-Public#97]
When exiting flight mode while in VR it cases the game to crash

I have video but its just crashing when i click flight to stop flying

**Comment by rakosi2** [comment]
Try deleting the MelonLoader folder and version.dll and reinstalling MelonLoader 2.7.2

**Comment by UiharuKazari2008** [comment]
Tried reinstalling melon loader completely and same thing occurred. Only difference is that you can toggle it once but after that it’s a crash

**Comment by rakosi2** [comment]
Could you post your latest MelonLoader log file here? You can find it in VRChat\Logs.
