### ISSUE TITLE
[BUG] Screenspace shader not working in third person 

### ISSUE THREAD

**Issue by RiskiVR** [emmVRC/emmVRC-Public#98]
I used to use third person on desktop to test screenspace shaders to see how they look, however they recently stopped working properly when in third person.

**Comment by BenjaminZehowlt** [comment]
Screenspace shaders are written with the assumption your camera will always be first person, we can’t really do much to fix this without some potentially very hacky workarounds

**Comment by RiskiVR** [comment]
This was 2 years ago lol
